### ISSUE TITLE
Arduino usb.Task() function blocks code

### ISSUE THREAD

**Issue by courtlife** [felis/USB_Host_Shield_2.0#106]
Hello,

I'm using my arduino to bring in serial data from the usb on the Due board, and I also have a touchscreen that i use to display information and allow the user to select a few options. In my main loop I call usb.task() and genie.DoEvents. (I have a 4d systems display). The problem is that if usb.task() doesn't see any data it blocks all calls indefinitely. The arduino site says for 5 seconds, but its irrelevant in this case because it does nothing.

So the real issue i'm having is that if the usb device is not sending serial data (which most of the time it isn't) I'm completely unable to interface with my setup via the screen because the arduino is just waiting for the usb to send something. I tried running a while loop that would kick back and restart the loop every 200 mseconds but that failed, and I also tried scheduler to have 2 loops running one for the screen and one for the usb.task function, but that didn't work either. any help here?

I'm using the Due and the newest Arduino IDE 1.5.8 i believe If it helps to attach code I can do that as well. I need to stop this task function from being a nuisance! 

Thanks in advance!

**Comment by LiberAC** [comment]
Hey @courtlife did you have any advance on this?, I just came across this same issue, I'm using the USB Host Library Rev.2.0 on an arduino UNO rev 3

**Comment by pietervandermeer** [comment]
@courtlife I recently also experienced the 5 s blocking delay of USBHost.Task() also on Arduino DUE.. the 5 seconds are the recommended time-out from the USB standard. so, the programmers weren't wrong in that respect. however, to leave a task blocking in a real-time/embedded environment.. they should have made proper state machines that return as quickly as possible.. 

but that's not the case here. so, you can do two things: 
1) run this baby in an interrupt.. independent of loop() (or vice versa: run main code in an interrupt and usb.task in loop()) .. setting up an interrupt using a Timer/Counter isn't that hard.
2) modify the code to not use the 5s time-out, but for instance a 10 ms one.. you can hack USBHost::dispatchPkt() to achieve this. this is the easiest solution, and i guess most USB devices are quick enough to warrant such a solution. it works for me.

**Comment by xxxajk** [comment]
Or you can wait for the 3.0 version of the library, which does things in an ISR :-)

**Comment by pietervandermeer** [comment]
@xxxajk I'll await that. Will the user be (somewhat) free to select an ISR of his choice?

**Comment by xxxajk** [comment]
Yes, it is actually an optional parameter to pass.

On Tue, Mar 3, 2015 at 4:50 PM, pietervandermeer <notifications@github.com>
wrote:

> @xxxajk <https://github.com/xxxajk> I'll await that. Will the user be
> (somewhat) free to select an ISR of his choice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/issues/106#issuecomment-77043836>
> .
>



-- 
Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by pietervandermeer** [comment]
cool

**Comment by xxxajk** [comment]
One other note, the new library also allows multiple hosts. email me if you want to play.

**Comment by pietervandermeer** [comment]
if time allows... i would certainly give it a shot. :)

one more question: does your lib use the SAM3X DMA controller in any way?

**Comment by xxxajk** [comment]
No. It also does not (yet) support the sam3x native USB. It does support the max chip, and Kinetis USB so far. SAM support is planned, but I'd need to know how to push the built-in stuff out of the way without having to do any modifications to the installation.

**Comment by xxxajk** [comment]
Looking closer at the due stuff, it is a library... I should be able to port this pretty easily, and I have a due to test it on too. :smiley:

**Comment by pietervandermeer** [comment]
For me you don't have to bother. I was just worried that since I'm using the DMA for different things it might clash with USB transfers.. But i guess having an enable flag for DMA would be pretty sweet. Right now I'm only using keyboard, but usb stick would be very nice as well. :) :) Anyway, thanks for your help!

**Comment by xxxajk** [comment]
Actually in the current development version, the only two devices working at the time of this writing are hubs and bulk storage (thumb drives, cdrom, etc).

**Comment by pietervandermeer** [comment]
ok. but also HID's are supported already, right (seeing the contents of this repo)?

**Comment by xxxajk** [comment]
HID is supported in 2.0, and will be supported in the next version.

**Comment by Lauszus** [comment]
Closing this issue, as it was not really relevant for this project, but the one bundled with Arduino which is based on 1.0.

@pietervandermeer if you want to help out testing the new library please see: https://github.com/felis/UHS30.

**Comment by AVRDen** [comment]
in **USB.h**:
_#define USB_XFER_TIMEOUT		5000_
Changing _5000_ to _50_ solved the problem for mouse and keyboard for me.
Stable work is not guaranteed with other usb devices.
