### ISSUE TITLE
testusbhostFAT.ino:55:18: fatal error: xmem.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by langwan** [felis/USB_Host_Shield_2.0#112]
No such file

**Comment by dalwinder1578singh** [comment]
hai I am new and another victom of error 11   ;27 fetal error xmem.h no such directry or file exist. but it is there what is the deal. Thanks

**Comment by xxxajk** [comment]
go to the url above, download it, install it into your personal libraries.This demo also REQUIRES the expanded RAM.
