### ISSUE TITLE
PS4BT PS4 Controller

### ISSUE THREAD

**Issue by langwan** [felis/USB_Host_Shield_2.0#114]
i using ps4 controller show this message

```
PS4 Bluetooth Library Started
Bluetooth Dongle Initialized
No response to HCI Reset
HCI Reset complete
Write class of device
Local Bluetooth Address: 00:1A:7D:DA:71:0B
Please enable discovery of your device
Gamepad found
HID device found
Now just create the instance like so:
BTHID bthid(&Btd);
And then press any button on the device
Connecting to HID device
Connected to HID device
Received Key Request
Bluetooth pin is set too: 0000
Pairing successful with HID device
Send HID Control Connection Request
Unknown Device Connected - VID: 054C PID: 05C4
BTD Init Failed, error code: D1
```

Note:
branch master or PS4BT as same as

**Comment by AliShaikh94** [comment]
I am getting this exact same error. I can get it to successfully pair, but no output

**Comment by Lauszus** [comment]
@AliShaikh94 please enable serial debugging: https://github.com/felis/USB_Host_Shield_2.0#enable-debugging and post the output.

**Comment by AliShaikh94** [comment]
So it's really quite weird. 
If I unplug the arduino, plug it back in, and then start the DS4, it works. The deep blue light comes on and vibrates as it should, just like wired. 

However, if I then turn on serial monitor, it stops working immediately, and then never works again until I unplug/replug the arduino. 

This is the serial output: 
PS4 Bluetooth Library Started
Bluetooth Dongle Initialized
HCI Reset complete
Write class of device
Local Bluetooth Address: 5C:F3:70:65:43:80
Wait For Incoming Connection Request
Gamepad is connecting
Incoming Connection Request
Remote Name: Wireless Controller
PS4 controller is connecting
Connected to Device: 00:01:6C:87:67:B2
Send HID Control Connection Request
Bluetooth pin is set too: 0000

Yet, the light is just the light blue one, and there is no vibration. The fact that it works at first is very confusing.

**Comment by Lauszus** [comment]
@AliShaikh94 it looks like they might have changed something since the first release of the DS4 controller. Please see the following issue: https://github.com/felis/USB_Host_Shield_2.0/issues/273.

**Comment by caliptox** [comment]
merhaba ben DS4 kolunu ardunio ile bağlamaya çalışıyorum. Bluetooth CSR 4.O kullanıyorum. Ancak serial monitörde Bluetooth Library started yazıyor başka bir yazı gelmiyor. Hata ayıklamayı etkinleştirdim
