### ISSUE TITLE
an error appeared when i Compile the examples

### ISSUE THREAD

**Issue by shiyu460** [felis/USB_Host_Shield_2.0#119]
when i Compile the examples an error appeared like this:
D:\arduino-1.5.3-Intel.1.0.4\hardware\arduino\edison\cores\arduino/WString.h:37:93: error: 'PSTR' was not declared in this scope
 #define F(string_literal) (reinterpret_cast<const __FlashStringHelper *>(PSTR(string_literal)))
                                                                                             ^
XBOXUSB.ino:20:18: note: in expansion of macro 'F'

i use intel Edison. so what shuld I do ?

**Comment by Lauszus** [comment]
@shiyu460 I added support for the Intel Edison at the following branch: https://github.com/felis/USB_Host_Shield_2.0/tree/Galileo. Please download it, test and report back.

**Comment by Lauszus** [comment]
Closing this in favour of: https://github.com/felis/USB_Host_Shield_2.0/issues/132.
