### ISSUE TITLE
Xbox 360 missed events?

### ISSUE THREAD

**Issue by davidsiracusa** [felis/USB_Host_Shield_2.0#123]
I have a wireless Xbox 360 adapter, 2 Xbox controllers, Arduino Uno R3, and USB Host shield.

I noticed sometimes when I release the thumb hat on the Xbox 360 controller (or other analog controls) quickly that it appears to miss an event. For example I repeatedly move the right hat to the right, and quickly release several times. I may end up with a final value of 32k or in the 10's of k, rather than an expected near center value.  Not easily reproduced, however it happened often enough in an application to be noticeable.

I've tried Xbox controllers, they have fresh batteries. I enabled debug tracing (EXTRADEBUG, PRINTREPORT), nothing stands out as a cause.
  
I haven't seen this behavior using a raspberry pi b+ (xboxdrv) or with a sample .NET program I compiled.

**Comment by Lauszus** [comment]
Closing due to lack of feedback.
