### ISSUE TITLE
Long delay to initialize USB drives

### ISSUE THREAD

**Issue by greiman** [felis/USB_Host_Shield_2.0#124]
Is there a way to shorten the time to initialize mass storage devices?  The time to get to USB_STATE_RUNNING can be very long.

The code below takes about 45 seconds to initialize a SanDisk 8 GB cruzer, 25 seconds for a 4 GB SanDisk blade.  A 16 GB Corsair Voyager GO is faster at 6 seconds.

Here is output:
Cruzer:
USB state: 20, ms: 0
USB state: 40, ms: 200
USB state: 50, ms: 250
USB state: 51, ms: 250
USB state: 90, ms: 45773
sector size: 512
Blade:
USB state: 20, ms: 0
USB state: 40, ms: 200
USB state: 50, ms: 250
USB state: 51, ms: 250
USB state: 90, ms: 25739
sector size: 512
GO:
USB state: 20, ms: 0
USB state: 40, ms: 200
USB state: 50, ms: 250
USB state: 51, ms: 250
USB state: 90, ms: 5722
sector size: 512

Here is the test program:
#include \<masstorage.h>
USB usb;
BulkOnly bulk(&usb);
void setup() {
 uint8_t last_state = 0;
 uint8_t current_state;
  Serial.begin(9600);
  
  while (usb.Init(1000) == -1) {
    Serial.println(F("No USB HOST Shield?"));
  }
  usb.vbusPower(vbus_on);
  uint32_t m = millis();
  do {
    usb.Task();  
    current_state = usb.getUsbTaskState();   
    if (last_state != current_state) {
      Serial.print(F("USB state: "));
      Serial.print(current_state, HEX);
      Serial.print(F(", ms: "));
      Serial.println(millis() - m);
    }
    last_state = current_state;  
  } while(current_state != USB_STATE_RUNNING);
  Serial.print(F("sector size: "));
  Serial.println(bulk.GetSectorSize(0));
}
void loop() {}

**Comment by Lauszus** [comment]
This issue will be solved in: https://github.com/felis/UHS30, as it use ISR or at least it will be improved.
