### ISSUE TITLE
Error with arduino mega

### ISSUE THREAD

**Issue by EscuderoKevin** [felis/USB_Host_Shield_2.0#126]
En:

Hello friends, When I connect the USB HOST SHIELD V1.4 ElecFreaks.com, and by the example code that is here for ps3 joystick, the screen just shows me

OSC did not start.

Any solution for this? Thank You!

Spanish:

Hola amigos, Cuando conecto el USB HOST SHIELD V1.4 de ElecFreaks.com, y cargo el codigo de ejemplo que esta aca para el joystick de ps3 , simplemente la pantalla me muestra

OSC did not start.

Alguna solucion para esto ? Gracias!

**Comment by Lauszus** [comment]
Was this issue solved?

**Comment by EscuderoKevin** [comment]
No. Its no compativle w mega

24/03/2015 escribió:
>Was this issue solved?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/felis/USB_Host_Shield_2.0/issues/126#issuecomment-85741602

-- Enviado desde mi teléfono con K-@ Mail.

**Comment by Lauszus** [comment]
I'm sitting with an Arduino Mega in front of me and it's working just fine with the official shield. Please report  this bug at the place where you bought your shield.

Please considering buying the official shield in the future in order to support the actual developers of the hardware and library.
