### ISSUE TITLE
I have a question with adk.h and adk.cpp.

### ISSUE THREAD

**Issue by lowfiend** [felis/USB_Host_Shield_2.0#127]
Dear:

Is USB_Host_Shield_2.0  support AOA2.0?

https://source.android.com/accessories/aoa2.html

Thanks a lot

**Comment by q2dg** [comment]
Has AOA/ADK future? It seems pretty abandoned by Google from 2012... (but maybe I'm wrong)

**Comment by Lauszus** [comment]
@q2dg yeah Google does not seem to much invest much time and recourses in it.

**Comment by Lauszus** [comment]
Closing this issue, as it does not seem like anyway is using AOA 2.0 anyway.
