### ISSUE TITLE
Wired Xbox Controller Not Working

### ISSUE THREAD

**Issue by SpencerLittle** [felis/USB_Host_Shield_2.0#128]
I'm relatively new to Arduino and am having difficulties. I'm using an Arduino Uno with a SainSmart USB host and am trying to get a wired Xbox 360 controller simply to work off of the example code given. What happens is when I upload the code, the controller blinks the LED's once and when I open the console it reads "XBOX USB Library Started", the controller will blink again, and then nothing will happen or display on the console window. I'm not sure what exactly is going on. I've tried external power via a wall adapter with 9V at 1A but nothing helps. Please help and thanks.

**Comment by Lauszus** [comment]
Please enable serial debugging: https://github.com/felis/USB_Host_Shield_2.0#enable-debugging and post the output.

**Comment by SpencerLittle** [comment]
Well the good news is it is doing something now. The bad news is it isn't in my favor.
Now it says:

XBOX USB Library Started
Unknown Device Connected - VID: 162E PID: BEEF
Xbox 360 Init Failed, error code: D1

Not sure exactly what that means nor what error code D1 is.

**Comment by Lauszus** [comment]
Try to comment out the following line: https://github.com/felis/USB_Host_Shield_2.0/blob/master/XBOXUSB.cpp#L108-L109 and tell me if it works.

**Comment by SpencerLittle** [comment]
That seemed to do the trick. Thank you so much and I'll let you know if anything else comes up.

**Comment by Lauszus** [comment]
I just added support for it properly: https://github.com/felis/USB_Host_Shield_2.0/commit/96dfd7e37d395a70d3d8c1bf211eaa8323b2d857. Please redownload the library and confirm that it's working.

**Comment by SpencerLittle** [comment]
I apologize for my delayed response. The new library works fine. It actually worked the first upload without any problems.

**Comment by Lauszus** [comment]
@SpencerLittle thanks for your feedback ;)
