### ISSUE TITLE
Wired XBOX controller

### ISSUE THREAD

**Issue by fred42** [felis/USB_Host_Shield_2.0#130]
I downloaded the library for the USB Host Shield to use the XBOXUSB library to try and run an XBOX controller through an arduino and USB Host Shield. I've had problems getting the example sketch to work, though. Whenever I run the code and open up the Serial Monitor, I get the response that OSC did not start. I've tried testing both the controller and the arduino and shield, and they all work fine by themselves, but I can't seem to get them to work together for this sketch. How do I fix this problem?

**Comment by Lauszus** [comment]
What shield are you using?

**Comment by xxxajk** [comment]
I think we are starting to need a general FAQ about these other
incompatible boards...
That said; there are only a few boards that are indeed 100%
clones/compatible.

First, if your board lacks the ICSP connection to your arduino, then we
can't help you software-wise. This means you will have to do the required
modifications to your board yourself.
If you can't do hose modifications, we recommend that you send the board
back to the place where you bought it from, and buy a genuine USB Host
Shield from circuits@home or other authorized dealer. Buying the real
product helps us help you by funding software development.


On Thu, Jan 15, 2015 at 11:19 AM, Kristian Sloth Lauszus <
notifications@github.com> wrote:

> What shield are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/issues/130#issuecomment-70111590>
> .
>



-- 
Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by felis** [comment]
We already have a page listing compatible BT dongles. This text can be added there and page can be made into a FAQ.

**Comment by xxxajk** [comment]
We still should place a big fat warning about shields that are not from
circuits@home right here on github, in the readme...


On Fri, Jan 16, 2015 at 12:23 AM, Oleg Mazurov <notifications@github.com>
wrote:

> We already have a page listing compatible BT dongles. This text can be
> added there and page can be made into a FAQ.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/issues/130#issuecomment-70209796>
> .
>



-- 
Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by fred42** [comment]
I don't know exactly what the shield is called, but it is the USB Host Shield for Arduino that I found on linksprite.com

**Comment by Lauszus** [comment]
@fred42 sorry but that shield is not supported. Please support us by buying the official shield at either: http://www.circuitsathome.com/products-page/arduino-shields or http://shop.tkjelectronics.dk/product_info.php?products_id=43.

**Comment by mgeorgedeveloper** [comment]
Just wasted two days before randomly coming across this. I also have a USB host shield that says "www.linksprite.com" on it, that I bought from Maplin. I got past the "OSC did not start" issue by powering the Arduino/shield via external adapter or through vin, but then the next issue is that Xbox.Xbox360Connected line never goes true, neither does Xbox.XboxReceiverConnected for the wireless controller example code.

So the question is, will this solve my issue:

http://store.arduino.cc/index.php?main_page=product_info&cPath=37_5&products_id=541

I'm hoping to buy locally in the UK.

Thanks in advance for any advice.

**Comment by Lauszus** [comment]
No please buy the official shield from either: http://shop.tkjelectronics.dk/product_info.php?products_id=43 or http://www.circuitsathome.com/products-page/arduino-shields.

**Comment by xxxajk** [comment]
http://store.linksprite.com/usb-host-shield/
Is this your board? 
As far as I can tell, this should work on an __UNO ONLY__ and *possibly* with the ancient 1.0 library
Worse, it is a VERY old design :-) and it does not help us at all to buy such broken clones.

**Comment by xxxajk** [comment]
Nice cross post :-) Someone needs to tell linksprite that their product is not compatible.
@mgeorgedeveloper Get your money back if you can for that clone board.

**Comment by mgeorgedeveloper** [comment]
@Lauszus - "No please buy the official shield from either...."

This is really confusing, because this page:

http://arduino.cc/en/Main/ArduinoUSBHostShield

Has clear references to the library:

"The Arduino USB Host Shield can be used with the "USB Host Library for Arduino" hosted by Oleg Mazurov and Alexei Glushchenko from circuits@home, Kristian Lauszus and Andrew Kroll on GitHub (download)."

And also specifically states all the controllers as supported:

"-HID devices: keyboards, mice, joysticks, etc. 
-Game controllers: Sony PS3, Nintendo Wii, Xbox360. 
......
"

Are they not telling the truth?

#consumerminefield

**Comment by Lauszus** [comment]
Yes it is supported, but if you want to support us, the people who have actually written the code, then please buy the shield from one of us.

**Comment by mgeorgedeveloper** [comment]
Ah thanks for clarifying. It's basically down to me being impatient, and wanting this thing delivered next day - so I'm buying locally (UK). I'm assuming from the $ pricing that the board you're selling would be coming from the USA? Apologies if I made the wrong assumptions here.

Can you point me to the correct donations page for supporting this project directly?

**Comment by Lauszus** [comment]
Okay no problem. You can donate directly to us here: https://github.com/felis/USB_Host_Shield_2.0#donate.

**Comment by jwhitmarsh** [comment]
@mgeorgedeveloper did you ever get your board to work? I've just gone through the same thing as you.  I'm not trying to avoid supporting the developers - I just didn't realise this shield wasn't supported.

**Comment by mgeorgedeveloper** [comment]
@jwhitmarsh sorry didn't see this until now. It's been a while, so I can't actually remember how it worked out in the end. Sorry I couldn't be of more help.
