### ISSUE TITLE
problem with USB bluetooth dongle to connect ps3 controller ?

### ISSUE THREAD

**Issue by nmn11** [felis/USB_Host_Shield_2.0#133]

**Comment by Lauszus** [comment]
Can you give some more information? I will close this for now. Reopen if needed.

**Comment by nmn11** [comment]
My bluetooth usb dongle could not be detected in the library  usb host shield 2.0  - >> bluetooth--- >> PS3BT ?
Can you give me some information to bluetooth dongle suitable for usb-host master library 2.0..??

**Comment by Lauszus** [comment]
Please enable serial debugging: https://github.com/felis/USB_Host_Shield_2.0#enable-debugging and post the output, so I can see what is going on.

**Comment by nmn11** [comment]
OK, thank's very much for your information.. i have try it..
now,my bluetooth dongle can be used but why my ps3 controller dualshock can
not pair with it... example like that on image 111.PNG and my ps3
controller always blink...

**Comment by Lauszus** [comment]
Have you followed the paring procedure as described here: https://github.com/felis/USB_Host_Shield_2.0#ps3-library?

**Comment by Lauszus** [comment]
Btw I can't see the image.

**Comment by nmn11** [comment]
like that,..
![111](https://cloud.githubusercontent.com/assets/10902649/6141045/a275c6de-b1d2-11e4-99be-77fb0d3ab31e.PNG)

please help me !!

**Comment by nmn11** [comment]
I've done it according to the procedure as above. but always still like that...

**Comment by Lauszus** [comment]
This is a problem with your dongle, as it doesn't support 2.0+EDR, so the last data sent from the controller is not received.

There is nothing else to do than to try another dongle. A list is available here: https://github.com/felis/USB_Host_Shield_2.0/wiki/Bluetooth-dongles.
