### ISSUE TITLE
Usb library not working for mega adk

### ISSUE THREAD

**Issue by kiranjotcgc** [felis/USB_Host_Shield_2.0#138]
hi 
i am using mega adk on arduino 1.6.0
i  am trying to connect usb mouse with adk 
i downloaded the library but all the times i upload code it gives error called

Osc did not start 

please help

**Comment by Lauszus** [comment]
Have you selected "Arduino Mega ADK" in the boards menu?

**Comment by kiranjotcgc** [comment]
yes i have
honestly speaking it worked once
after that this error start coming

**Comment by Lauszus** [comment]
I just tried it with my Arduino ADK and it works fine.

Make sure that you have selected it in the boards menu. If it still does not work, then contact the place where you bought it.
