### ISSUE TITLE
PS4 Controller Audio Control

### ISSUE THREAD

**Issue by zardchim** [felis/USB_Host_Shield_2.0#140]
Hi All!

I am using a PS4BT with the shield and is looking for method to output sound like "beep-beep" through the small-speaker on the controller. 

I found there is are functions that can return the audio status, I wonder if we are able to send any sound command to the controller? 

Thank you in advance!

**Comment by Lauszus** [comment]
@zardchim no this is currently not supported. If you can find anywhere where somebody got it working with a computer let me know and I will figure out how they did it and then implement it in the library.

**Comment by zardchim** [comment]
@Lauszus  Okay!
