### ISSUE TITLE
Send data issue

### ISSUE THREAD

**Issue by ahmed-belal** [felis/USB_Host_Shield_2.0#158]
My application is set up to continuously send a constant string to the Android phone when it is connected in peripheral mode. However for some reason the first time the during teaches the phone correctly but all subsequent transmissions, although they report correct number of bytes read, have byte values 0x00 for each byte. Any ideas what might be going wrong?

**Comment by felis** [comment]
Perhaps, you have an error in your code?

**Comment by ahmed-belal** [comment]
Tried paying the same SndData line twice. The first call gets data through
and all subsequent calls deliver bytes 0x00

**Comment by Lauszus** [comment]
Have you tried the following example: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/adk/ArduinoBlinkLED/ArduinoBlinkLED.ino and the Android app that is meant for it: https://github.com/Lauszus/ArduinoBlinkLED?
