### ISSUE TITLE
Phone reconnection issue

### ISSUE THREAD

**Issue by ahmed-belal** [felis/USB_Host_Shield_2.0#159]
I have a host shield which I'm pretty sure it's not the official shield. I don't have access to a sparkfun shield either. Anyway whenever I connect the Android phone to my Uno via the shield, it connects properly. If I disconnect and reconnect it does not communicate and adk reports device isn't ready. The phone doesn't connect again until the board is reset.

**Comment by Lauszus** [comment]
Have you tried to connect an external power supply to the Arduino? Also it might be a problem with the shield, as the Chinese clones seems to have all kind of weird issues.

**Comment by ahmed-belal** [comment]
@Lauszus there isn't power issues, I've connected 9v and 12v adapters at times, the arduino side does not brown out or reset on connection or reconnection. It always defaults to error E0: Additional_Reset_Required for any connection after the first time I disconnect. Any ideas?

**Comment by ahmed-belal** [comment]
@Lauszus also the board passed all tests, runs all hr examples properly but has the same reconnection issue on blink led example.

**Comment by Lauszus** [comment]
You should try with the official shield, as it works fine on my setup.

**Comment by Lauszus** [comment]
Also have you tried another phone?

**Comment by ahmed-belal** [comment]
@Lauszus I have tried with the official shield as well and I still have this issue.

**Comment by Lauszus** [comment]
@ahmed-belal have you tried another Android phone?
