### ISSUE TITLE
Can i use this library with Dragino Yun shield

### ISSUE THREAD

**Issue by dinaras** [felis/USB_Host_Shield_2.0#165]
Hello,

Thank you for all the work done here. I am quite new to arduino, so much to learn.

I have built a small self balancing robot using an arduino UNO. I just got a dragino yun shield. Can i use this library with an UNO and the dragino shield and usb dongle in order to steer my robot?

Thank you very much in advance
Regards

**Comment by Lauszus** [comment]
Yes that should be possible, but remember that the shield is using 13-9 for communication with the shield. If you need to use pin 9 and 10 they can be rewired: https://github.com/felis/USB_Host_Shield_2.0#interface-modifications.
