### ISSUE TITLE
CP210x to host shield?

### ISSUE THREAD

**Issue by josb86** [felis/USB_Host_Shield_2.0#176]
Hi can be connected a CP210x to this shield, I have a device that have a CP210x and I need connect this to my arduino, is it compatible?. other question, thes shield is compatible with a DUE? I know that the DUE have host but in this port I have connected a keyboard.

**Comment by felis** [comment]
There is no support for CP210x yet. Several developers expressed interest in developing one; however, the code is yet to materialize.

**Comment by tobozo** [comment]
Seems like it's been [implemented](https://github.com/henla464/USB_Host_Shield_Library_2.0), not sure if this is valid though, will give a try
