### ISSUE TITLE
Mass Storage on Teensy 2.0

### ISSUE THREAD

**Issue by custodium** [felis/USB_Host_Shield_2.0#180]
Hello, It's possible use Mas Storage functions on Teensy 2.0?

Best regards.

**Comment by xxxajk** [comment]
If it reports as bulk storage and contains the minimum scsi command set,
yes. I still need to find this out myself. If you are only using mass
storage, you may like uhs 3 better, since it takes care of the fine details
for you.

**Comment by custodium** [comment]
I meant if the testusbhostFAT example will work on Teensy 2.0 with Atmega32u4

**Comment by xxxajk** [comment]
Short answer: yes, just use a usb-mini or full-sized shield.

**Comment by xxxajk** [comment]
Additional note: Memory will be an extremely scarce resource.
You may not be able to do some operations, so don't expect too much.

**Comment by custodium** [comment]
A lot of thanks Andrew, we are going to test it, we only need some basic tasks like read byte each byte some files and something else (not mapping files, directories or something else)

**Comment by Lauszus** [comment]
It seems like this issue was solved, but never closed, so closing it now.
