### ISSUE TITLE
Arduino Mega & Sparkfun USB Host Shield

### ISSUE THREAD

**Issue by brksnn** [felis/USB_Host_Shield_2.0#191]
Hi Guys,

I am trying to control my Snopy joystick with a Sparkfun USB host shield on Arduino Mega. I getting the following error from "USBHID_desc" code.

Start
OSC did not start.

However, I have searched a lot of things for hours and I tried the followings.

1- jumper RST with D7
2- Used external 5V power
3- Jumper the followings
    10 > 53 (SS)
    11 > 51 (MOSI)
    12 > 50 (MISO)
    13 > 52 (SCK)
4- uncomment the "#define BOARD_MEGA_ADK" in avrpins.h
5- Tried to add the following lines before void setup.
    //Revision 1.2 (DEV-09628)
    #define MAX_RESET 8 //MAX3421E pin 12
    #define MAX_GPX   7 //MAX3421E pin 17

Please Help!!!...

**Comment by felis** [comment]
Sparkfun board is not compatible with UHS code - try their forum for modding ideas.
