### ISSUE TITLE
Arduino Mega + Keyes USB Host Shield

### ISSUE THREAD

**Issue by brksnn** [felis/USB_Host_Shield_2.0#197]
Hi Guys,

I am trying to control my joystick with Keyes USB Host Shield from funduino.com (Tinkbox.ph). I think this board is totally clone of the original one. In my first trial, I got the following error;

Circuits At Home 2011
USB Host Shield Quality Control Routine
Reading REVISION register... Die revision invalid. Value returned: FF
Unrecoverable error - test halted!!
0x55 pattern is transmitted via SPI
Press RESET to restart test

After many unsuccessful Sparkfun board trials, I just bought this one. Its manual also says that this board is totally compatible with your library. I think I miss something. The solutions or the comments about this error are mainly related with Sparkfun board but this board is so compatible with yours.

Looking forward to your help!!!

Best...

**Comment by felis** [comment]
We don't support clones here. The board should work though, you might have gotten a bad one.
