### ISSUE TITLE
Two Slave Devices Example

### ISSUE THREAD

**Issue by lanceingle** [felis/USB_Host_Shield_2.0#204]
I want to read the reports from a USB mouse and keyboard for my Arduino project.

I feel like I'm almost there. I have written a custom HID report parser (following this blog post https://www.circuitsathome.com/mcu/hid-joystick-code-sample) for my Logitech Mx510 mouse so I could get all the buttons (the boot mouse example doesn't pick up all 8 buttons). I also tested the bootKeyboard example and it works with my keyboard.

Where my problem is I can't seem to figure out how to combine the two sketches. Is there a good example of this kind of project anywhere? I combined the two sketches and it compiles and loads. However, no matter which device is plugged in the mouse parser gets called.

I concatenated all my classes into a gist so you guys can check it out.
https://gist.github.com/lanceingle/1dc49a92714562db10af

Thanks for your time and advice
// lance

**Comment by Lauszus** [comment]
The following example demonstrates how to use a mouse and keyboard at the same time: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/HID/USBHIDBootKbdAndMouse/USBHIDBootKbdAndMouse.ino.
