### ISSUE TITLE
How frequently do I have to call Usb.Task()?

### ISSUE THREAD

**Issue by joseangeljimenez** [felis/USB_Host_Shield_2.0#208]
I had some issues in my code due to not calling Usb.Task() frequently enough. By experimenting with different USB devices, I found that it is acceptable calling Task() at least once every 10-15ms. I also found that a delay of hundreds of ms caused the Arduino to hang out...

Hence, my question: how frequently do you advise calling Usb.Task()?

**Comment by Lauszus** [comment]
It depends on the specific device. You can read the bInterval which is the polling interval from the endpoints, as it is done in the BTD class: https://github.com/felis/USB_Host_Shield_2.0/blob/master/BTD.cpp#L326-L357.
