### ISSUE TITLE
Accessing the USB stream?

### ISSUE THREAD

**Issue by spurra** [felis/USB_Host_Shield_2.0#211]
I've bought the UBS host shield for arduino and am attempting to access the USB byte stream (similar like Serial.read() or Serial.write()). I've come across your library which I think is by the same people who design the shield. However, I cannot seem to find a library function or similar which allows me to do this. Could anyone point me in the right direction?

**Comment by Lauszus** [comment]
@spurra all the low-level stuff is in here: https://github.com/felis/USB_Host_Shield_2.0/blob/master/UsbCore.h and https://github.com/felis/USB_Host_Shield_2.0/blob/master/Usb.cpp. Maybe you can try to describe what you want to achieve, then I might be able to help you better.

**Comment by spurra** [comment]
Thanks for pointing that out. Basically what I'm attempting is having a device connected to the USB host shield, read out the data it sends, modify it, and send it to my computer.

**Comment by Lauszus** [comment]
@spurra if you do not have any experience with the USB protocol it might be a bit complicated, as you need to make the microcontroller show up as a USB device, so the computer see it as a printer and then write a USB host driver in order to communicate with the printer.

**Comment by spurra** [comment]
I am sorry to reopen this again, but I really need an answer. Is the only thing the files UsbCore.h and Usb.cpp do, is implementing the USB protocol? If that is the case, it should be sufficient to read up on the USB communication protocol to understand the code, correct?

**Comment by Lauszus** [comment]
@spurra yes it's only in those files.

**Comment by Vamshi253** [comment]
Hi Spurra,

Have you been successful in establishing the communication between Printer and Arduino?

**Comment by spurra** [comment]
> Hi Spurra,
> 
> Have you been successful in establishing the communication between Printer and Arduino?

Unfortunately not.
