### ISSUE TITLE
Bluetooth dongle addition

### ISSUE THREAD

**Issue by bbf3** [felis/USB_Host_Shield_2.0#229]
Hey,
The TRENDnet TBW-106UB works correctly with a Sony PS3 controller (TBW-107UB is already on the list too).

As seen here: [Amazon.com](http://www.amazon.com/TRENDnet-Bluetooth-100Meters-Compatible-TBW-106UB/dp/B002AQSTXM)

Thanks,
Blake

**Comment by Lauszus** [comment]
@bbf3 thanks! I will add it to the list :)
