### ISSUE TITLE
USB host shield with Arduino and MC33926

### ISSUE THREAD

**Issue by xunisex** [felis/USB_Host_Shield_2.0#231]
Not sure if this is a hardware or software issue. I have the circuits at home usb host shield 2.0 hooked up to an Arduino UNO and a pololu mc33926 to control some motors with an xbox controller. After remapping a few pins here and there, I have everything working well together.  

In the sample code from the library, if I hold down either trigger, the rumble is activated, and the controller shakes until I release the trigger. I tried to modify this code to control motors1 and 2 with the left and right triggers, respectively. It works, but only briefly. After about three seconds of continuously holding in the triggers, the speed gets "locked in", and changing pressure on the triggers no longer effects the speed at which the wheels turn. Even if I release the triggers, the motors continue to move at that speed. Could this be an issue with the timer? Or maybe I need to add in a longer delay? The troublesome portion of the code follows below (in the loop function). Any suggestions would be greatly appreciated.

```
#include <XBOXUSB.h>

#ifdef dobogusinclude
#include <spi4teensy3.h>
#include <SPI.h>
#endif

USB Usb;
XBOXUSB Xbox(&Usb);

#include "DualMC33926MotorShield.h"
#include <PololuMaestro.h>
#include <SoftwareSerial.h>

SoftwareSerial maestroSerial(16,17);

DualMC33926MotorShield md;
MicroMaestro maestro(maestroSerial);

long int XboxLT;
long int XboxRT;

void setup() {
  Serial.begin(9600);
  maestroSerial.begin(9600); 
  md.init(); 
  md.setM1Speed(0); 
  md.setM2Speed(0); 
  #if !defined(__MIPSEL__)
    while (!Serial); // Wait for serial port to connect - used on Leonardo, Teensy and other boards with built-in USB CDC serial connection
  #endif
  if (Usb.Init() == -1) {
    Serial.print(F("\r\nOSC did not start"));
    while (1); //halt
  }
  Serial.print(F("\r\nXBOX USB Library Started"));
}
 
void loop() { 
  
  Usb.Task();
  if (Xbox.Xbox360Connected) {
     if (Xbox.getButtonPress(L2) || Xbox.getButtonPress(R2)) {
      XboxLT = map((Xbox.getButtonPress(L2)), 0, 255, 0, 300);
      md.setM2Speed(XboxLT);    
      XboxRT = map((Xbox.getButtonPress(R2)), 0, 255, 0, 300);
      md.setM1Speed(XboxRT);    
      delay(50);
    }else{
      md.setM1Speed(0); 
      md.setM2Speed(0); 
     }
}
}
```
I've since added in some serial.prints to check what is being returned by the triggers and motors, but there doesn't seem to be anything unusual that sticks out when the controller stops responding.

Thanks!
Mike

**Comment by Lauszus** [comment]
You should not have any delays in your code, as the USB device needs to be read continuously. Please read: https://www.arduino.cc/en/Tutorial/BlinkWithoutDelay and https://learn.adafruit.com/multi-tasking-the-arduino-part-1/using-millis-for-timing.

**Comment by xunisex** [comment]
Thanks!
