### ISSUE TITLE
Example of Manual Polling with HIDReportParser

### ISSUE THREAD

**Issue by lanceingle** [felis/USB_Host_Shield_2.0#233]
I have a working example of a sketch using the HIDReportParser class to parse reports from a Mx510 Logitech mouse. However, I want to poll the mouse manually. Is this possible? Currently, the Parse function only gets called when the mouse is moved. I want to call it myself in the loop function.

Thanks for your time,
// lance

**Comment by Lauszus** [comment]
@lanceingle no that is not possible. It is common for mice to only output something when it is moved.
