### ISSUE TITLE
Example code can not print devices

### ISSUE THREAD

**Issue by LSChyi** [felis/USB_Host_Shield_2.0#239]
Hello, I have used an Arduino pro mini usb host shield, and an Arduino pro mini with this library.
As I ran the example codes (I ran USB_Desc, USBHID_Desc, USBHIDBootKbd, BTHID), in the Serial monitor, it print "Start", but not further information, no matter I replugged without reboot, or plugged the usb device on the shield and reboot. Devices I have tried includes: Logitech keyboard K120, a joystick, bluetooth mouse.

The Arduino pro mini I use is not an official one, but the pins which are used by the shield are the same as the official pro mini(http://www.auctionzealot.com/members/rkellyp/promini.png). Also, I am sure the function Usb.Init() succeeded because the Serial monitor didn't print "OSC did not start".

Can you give some ideas? Thanks.

**Comment by Lauszus** [comment]
@LSChyi have you enabled serial debugging: https://github.com/felis/USB_Host_Shield_2.0#enable-debugging?

**Comment by LSChyi** [comment]
Thanks for your advises @Lauszus, I enabled it but Serial monitor still print "Start" without any other messages. =

**Comment by Lauszus** [comment]
Please try to connect an external power supply: https://github.com/felis/USB_Host_Shield_2.0#faq.

**Comment by LSChyi** [comment]
I used an y cable as and draw powers from my computer, but still the same

**Comment by Lauszus** [comment]
Please try the following example: https://github.com/felis/USB_Host_Shield_2.0/tree/master/examples/board_qc.

**Comment by LSChyi** [comment]
Thanks a lot!

Circuits At Home 2011
USB Host Shield Quality Control Routine
Reading REVISION register... Die revision 02
SPI long test. Transfers 1MB of data. Each dot is 64K................ SPI long test passed
GPIO test. Connect GPIN0 to GPOUT7, GPIN1 to GPOUT6, and so on
Test failed. Value written: 00 Value read: FF 
Press any key to continue...

So it fails at testing GPIO?

**Comment by Lauszus** [comment]
Just send any character to skip the test.

**Comment by LSChyi** [comment]
Now it sucks at "Waiting for device..."

**Comment by Lauszus** [comment]
Try to plug in your device.

**Comment by LSChyi** [comment]
Yes I did, but nothing happened(even I use Y cable as external power).

**Comment by Lauszus** [comment]
Hmm okay. What shield are you using?

**Comment by LSChyi** [comment]
I use Arduino pro mini usb host shield.

**Comment by Lauszus** [comment]
Where did you buy the shield?

**Comment by LSChyi** [comment]
I bought it from Taobao, and it says it is made in China. So it is very possible the chip has something goes wrong. Thanks for your help!

**Comment by Lauszus** [comment]
I would contact the dealer then, as there is clearly something wrong. You're welcome ;)
