### ISSUE TITLE
ps4 over usb shield to arduino 

### ISSUE THREAD

**Issue by arpeggio1234** [felis/USB_Host_Shield_2.0#242]
Hello interfacing with the PS4 controller i would like the L1 R1 and L3 and R3 knobs to have an on and off state instead of what they now are toggle when you make a  buttonclick and then make a call to PS4.getButtonClick(L1); 
I this possible, help me on the way please, can this be done by coding or do i have to modify the library,
Thanks in advance, Dian

**Comment by Lauszus** [comment]
Please use the getButtonPress function instead:
```C++
PS4.getButtonPress(L1);
```
