### ISSUE TITLE
PS3 Library (PS3BT): PS3 controller battery fully discharged

### ISSUE THREAD

**Issue by mpena2099** [felis/USB_Host_Shield_2.0#254]
Hi!

When the PS3 controller battery is fully discharged, I need to "set the bluetooth address of the dongle internally to the PS3 controller" again??? :-/

Thanks!
Mauricio

**Comment by Lauszus** [comment]
@mpena2099 I am actually not sure. A way to work around it, is just check the battery level of the controller and then disconnect it automatically if it is running low. Please see the ```getStatus``` method: http://felis.github.io/USB_Host_Shield_2.0/class_p_s3_b_t.html#a5062acbd19a52d88a998f19060fbc46a.
