### ISSUE TITLE
GPX PIN

### ISSUE THREAD

**Issue by didix21** [felis/USB_Host_Shield_2.0#256]
Where exactly is defined the GPX PIN and can I changed it? For example, I would like to change D8 by D3.

**Comment by Lauszus** [comment]
The GPX pin is not used by the library. Please read: https://github.com/felis/USB_Host_Shield_2.0#interface-modifications.

**Comment by xxxajk** [comment]
Actually it is used, for power control.

**Comment by Lauszus** [comment]
Oh yeah you are right :) But that is only if it is added, the default shield does not have a power switch.

**Comment by Lauszus** [comment]
Anyway it is handled in this file: https://github.com/felis/USB_Host_Shield_2.0/blob/master/usbhost.h. And here are the commits that added the support: https://github.com/felis/USB_Host_Shield_2.0/commit/b30c56a86e096ef3147cebc66e761f6ad2b1acfd and https://github.com/felis/USB_Host_Shield_2.0/commit/a57215fb727e481c75b6b4625c4c2f257a357e95.

**Comment by xxxajk** [comment]
It will try to use it on start up/init, after that, if it is unused, the user is free to reprogram it. UHS3 may not end up that way, though. There is no way to detect if the switch is actually present, which is a shame.
