### ISSUE TITLE
Bluetooth 4.0 dongle adapter

### ISSUE THREAD

**Issue by oivinds** [felis/USB_Host_Shield_2.0#264]
Will it work? Or is it only Bluetooth 2.0 that will work with the library.

**Comment by xxxajk** [comment]
Good question. Do you have one to try? If not, I'll see if I have one here.

**Comment by oivinds** [comment]
Thanks!, No I have not, but the local shop has only 4.0. I have though tried with a dongle based on Logitech unified receiver that (seemingly) did not work.

**Comment by xxxajk** [comment]
ok, I found one here. I'll let you know shortly.

**Comment by Lauszus** [comment]
Yes Bluetooth 4.0 dongles work with the library.

**Comment by xxxajk** [comment]
Mine doesn't, actually...
Vendor  ID:             19FF
Product ID:             0239
Revision ID:            0112

**Comment by xxxajk** [comment]
All interfaces on it are Vendor Specific Class, except the last one which is used for updating....
Even Linux hates it :8ball:

**Comment by xxxajk** [comment]
Apparently this particular dongle wants firmware sent to it.... lovely :-)
Just be aware of this.

**Comment by oivinds** [comment]
Thanks guys!
