### ISSUE TITLE
Following up #293

### ISSUE THREAD

**Issue by sawhim** [felis/USB_Host_Shield_2.0#296]
#include <PS4BT.h>
#include <usbhub.h>
#define ENABLE_UHS_DEBUGGING 1
// Satisfy the IDE, which needs to see the include statment in the ino too.
#ifdef dobogusinclude
#include <spi4teensy3.h>
#include <SPI.h>
#endif........

IS THAT WHAT YOU MEAN? if so i'm still getting the same result. Thanks for
helping out :)

**Comment by xxxajk** [comment]
https://github.com/felis/USB_Host_Shield_2.0/blob/master/settings.h#L27

That's where it is done for UHS 2.0
