### ISSUE TITLE
BT SPP Working with Windows 10? 

### ISSUE THREAD

**Issue by mjs513** [felis/USB_Host_Shield_2.0#300]
Was wondering if anyone has gotten SSP to work with WIndows 10.  I am able to pair the host shield with windows but when I use any of the Bluethooth serial apps I can not connect?  Is there a trick or one particular app that works.  Not a

**Comment by Lauszus** [comment]
Please enable serial debugging: https://github.com/felis/USB_Host_Shield_2.0#enable-debugging and post the output when you pair and when you try to connect to the serial port.

**Comment by Lauszus** [comment]
Closing due to lack of response.
