### ISSUE TITLE
Secure Bluetooth Connection for PS4_BT

### ISSUE THREAD

**Issue by vedangasDARKNINJA** [felis/USB_Host_Shield_2.0#306]
I'm having problems to pair PS4 with my USB HOST SHIELD when there are other bluetooth devices nearby sending a request to 'wireless controller' (PS4's name in the bluetooth list). How to have secure connection that will require a pin or something so that only bluetooth with that pin will connect to PS4

**Comment by Lauszus** [comment]
So other devices are connecting to the PS4 controller before the USB Host Shield does it? This is not something we can do anything about, as this is a limitation of the PS4 controller will accept any incoming paring request.

**Comment by vedangasDARKNINJA** [comment]
okay. thanks !
