### ISSUE TITLE
HID Joystick how to get input continuously?

### ISSUE THREAD

**Issue by gunnicus** [felis/USB_Host_Shield_2.0#310]
Hi I'm using the HID Joystick, I only get values in OnGamePadChanged event, if I push the joystick forward say to value 50, I want to continuously get value 50 instead of get it only once from the OnGamePadChanged event. What should I do? 

Thanks a lot.

**Comment by Lauszus** [comment]
My guess would be that the hardware only sends out data when they actually change, so there is nothing you can do about that on the software side.

However you could simply just store the last value in a variable then just use that in your loop?

**Comment by gunnicus** [comment]
I will have to do it that way, thank you sir.
