### ISSUE TITLE
Bluetooth compatible list needs to be updated

### ISSUE THREAD

**Issue by garybethel** [felis/USB_Host_Shield_2.0#311]
This list needs to be updated to remove the "GMYLE(R) Ultra-Mini USB Micro Bluetooth 4.0 Low Energy Wireless Dongle Adapter".
This dongle is will occasionally pair but has issues it would seem. Other have had issue too with it.

list 
https://github.com/felis/USB_Host_Shield_2.0/wiki/Bluetooth-dongles

**Comment by Lauszus** [comment]
Thank you. I have removed it from the list.
