### ISSUE TITLE
USBH_Midi bulk flag

### ISSUE THREAD

**Issue by vit3k** [felis/USB_Host_Shield_2.0#313]
`if ((epDesc->bmAttributes & 0x02) == 2) {//bulk`

I think this should be changed to:

`if ((epDesc->bmAttributes & 0x03) == 2) {//bulk`

because 0x02 mask will match bulk and interrupt modes and wrong endpoint will be used.

Bits 0..1 Transfer Type
00 = Control
01 = Isochronous
10 = Bulk
11 = Interrupt

**Comment by Lauszus** [comment]
Thank you! I can see that bug is actually in several drivers. I'll take a look at it later today.

**Comment by Lauszus** [comment]
See: https://github.com/felis/USB_Host_Shield_2.0/pull/314.

**Comment by YuuichiAkagawa** [comment]
novation Launchpad has illegal endpoint attribute.
This device reports bmAttributes.TransferType is 3. But it is bulk transfer device.
Old implementation is work fine with MIDI.  I will fix later.
```
if ((epDesc->bmAttributes & USB_TRANSFER_TYPE_BULK)) {//bulk
```

**Comment by vit3k** [comment]
So how can I then choose correct endpoint when I have both (bulk and interrupt) in my device (Boss Katana 100)?

**Comment by Lauszus** [comment]
@vit3k I agree, the code is correct as it is right now, but my guess is that @YuuichiAkagawa will make a special check for that particular device or create a fallback if the current implementation fails to initialise the device.

**Comment by YuuichiAkagawa** [comment]
@vit3k Please show me your descriptors using USB_desc.
