### ISSUE TITLE
Can USB Host Shield with Arduino Uno be used to communicate with a CDC USB device?

### ISSUE THREAD

**Issue by blah2222** [felis/USB_Host_Shield_2.0#317]
Hello, I have a USB CDC device that communicates with the PC via a virtual COM port. First use requires the installation of a virtual COM port driver.

Wondering if this device could communicate using the CDC ACM library with Arduino Uno + USB Host Shield?

Device manual:
http://www.harvardapparatus.com/media/manuals/Product%20Manuals/11%20Elite%20OEM%20Manual_5420-007REV1.0.pdf

Thanks!

**Comment by Lauszus** [comment]
Please try any of the provided examples: https://github.com/felis/USB_Host_Shield_2.0/tree/master/examples.
