### ISSUE TITLE
usb host on stm32L4 Dragonfly support

### ISSUE THREAD

**Issue by arpeggio1234** [felis/USB_Host_Shield_2.0#328]
I am trying to compile an Arduino usb hostshield for the STM32L4 based Dragonfly code and the compiler says ''please define board in avrpins.h''.
How can i do this, i am on Linux, manjaro, and found the avrpins.h file and see there is no 
STM32L4 entry, can i put it in, and yes what? Or can i use the teensy pinout for the dragonfly since they are lookalikes.

Thanks in advance, Dian from the Netherlands

**Comment by arpeggio1234** [comment]
Hello Kristian, thanks for making all this great stuff.For now just trying to send you a pm, more to come soon. Am trying to put usb shield on Dragonfly.
Dian from the Netherlands

----- Oorspronkelijk bericht -----
Van: Kristian Sloth Lauszus <notifications@github.com>
Aan: felis/USB_Host_Shield_2.0 <USB_Host_Shield_2.0@noreply.github.com>
Cc: arpeggio1234 <dianderocker@online.nl>, Author <author@noreply.github.com>
Verzonden: Mon, 27 Nov 2017 16:49:55 +0100 (CET)
Onderwerp: Re: [felis/USB_Host_Shield_2.0] usb host on stm32L4 Dragonfly support (#328)

Please checkout the pull request I did for the STM32F446 Nucleo board: https://github.com/felis/USB_Host_Shield_2.0/pull/178.

A PR is more than welcome!

**Comment by Lauszus** [comment]
You can find my contact details here on Github: https://github.com/Lauszus, but I prefer to keep the conversation here as an issue, so other can find it in the future.

**Comment by arpeggio1234** [comment]
Oh sorry you meant a pull request.
I was 'reading' a pm.
A pull request for the STM32L4 is a good idea. What csn i do to ask that, make it happen,  can i br of any help.
Many thanks again for yours concern.
Dian

**Comment by Lauszus** [comment]
@arpeggio1234 simply fork the repository and then start modifying the code. Then once you are done you can simply open up a pull request.

Sorry, but I have limited time at the moment to help you out. I would recommend you open up a pull request and then I'll help you a long the way.

**Comment by Lauszus** [comment]
I will close this issue, as I believe it has been solved.
