### ISSUE TITLE
Afterglow wireless PS3 controller connection issue

### ISSUE THREAD

**Issue by esbayonat** [felis/USB_Host_Shield_2.0#329]
I'm trying to connect a afterglow wireless PS3 controller with arduino and I'm trying the example PS3BT but it doesn't read the dongle that comes with the controller so I don't know how to do the connection. How do I do it? The controller doesn't have an option to connect with an USB cable. Thank you

**Comment by Lauszus** [comment]
It's probably just a regular HID device. Please checkout the provided examples: https://github.com/felis/USB_Host_Shield_2.0/tree/master/examples/HID.
