### ISSUE TITLE
USBHIDBootKbdAndMouse.ino in example does not work properly

### ISSUE THREAD

**Issue by ezura573** [felis/USB_Host_Shield_2.0#333]
Connected to the USB HOST shield with a self-powered USB HUB, where the keyboard and mouse are connected to that HUB, only the keyboard reacts, the mouse does not react.
However, if you connect the keyboard or mouse directly without using HUB, it works.

 And I also tried "USBHIDBootKbd.ino" and "USBHIDBootMouse.ino"
These two examples also worked with HUB.

**Comment by xxxajk** [comment]
What board are you using with the UHS?

**Comment by Lauszus** [comment]
Please see: https://github.com/felis/USB_Host_Shield_2.0/issues/334.
