### ISSUE TITLE
Documentation: Bad line linking in wiki.

### ISSUE THREAD

**Issue by Nurrl** [felis/USB_Host_Shield_2.0#342]
Hi, I noticed in the "[Setting PS3 Controller BT Address section](https://github.com/felis/USB_Host_Shield_2.0/wiki/PS3-Information#setting-the-bt-address-on-your-ps3-controller)" of **PS3 Information** wiki, that the line was pointing to *Line 12* instead of *Line 22*.

It should be a quick fix ;D

**Comment by Lauszus** [comment]
Thank you. It is now fixed.
