### ISSUE TITLE
How can we reroute SS and Int pins in code?

### ISSUE THREAD

**Issue by jsweet13** [felis/USB_Host_Shield_2.0#352]
Hello,

I'm browsing through all files in the 2.0 library to find the SS and Int pin Pi out for the Arduino Uno but not really having any luck.

I broke the connections and rerouted SS to pin A5 and rerouted INT to A0 on my Arduino Uno so I can display chars on a tftlcd display.

How do I reflect A5 and A0 pins in the USBcore.h file?

I see and changed this line to:
typedef MAX3241e<PA0, PA5> MAX3241E;

Is this correct? And are there regular variable names I can use to change the PIN numbers dynamically in code?

Thanks for your help.

**Comment by Lauszus** [comment]
Please see: #353.
