### ISSUE TITLE
Library for USB game steering wheel controller

### ISSUE THREAD

**Issue by igaoger** [felis/USB_Host_Shield_2.0#361]
Hi, 

Currently I am working on a small Arduino project using USB game steering wheel controller (no matter for PC, or Xbox or PS4) to control a wireless RC model car,  I am not sure the XBOXUSB or PS4UBS library works for me.

Have anyone done anything similar project？

**Comment by Lauszus** [comment]
Please see the following example: https://github.com/felis/USB_Host_Shield_2.0/tree/master/examples/HID/SRWS1.

You will need to modify the parse to match your steering wheel: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/HID/SRWS1/SRWS1.h.
