### ISSUE TITLE
Ps4 controller serial problem on power 

### ISSUE THREAD

**Issue by srknsntrk1991** [felis/USB_Host_Shield_2.0#362]
Hello 

I am trying to run a dc motor and ps4 controller which is connected to arduino uno r3 via usb cable. 

I debugged your example on my arduino and i run serial port screen and everything works well  and i can even arrange motor speed but when i remove my arduino from my computer and put it on power, ps4 controller doesnt work. 

I think there is a serial port problem about starting it. I would be very thankful if you could help me. 

Regards,
Serkan

**Comment by Lauszus** [comment]
Simply remove the following line:

```C++
while (!Serial); // Wait for serial port to connect - used on Leonardo, Teensy and other boards with built-in USB CDC serial connection
```

**Comment by srknsntrk1991** [comment]
Ahah yes i did it before you say :P Thank you so much

13 Mar 2018 22:05 tarihinde "Kristian Sloth Lauszus" <
notifications@github.com> yazdı:
