### ISSUE TITLE
GPLv3 Compatibility?

### ISSUE THREAD

**Issue by marcio-ao** [felis/USB_Host_Shield_2.0#364]
Hello,

We would like to incorporate the code from the USB Host Shield in the [Marlin firmware](http://marlinfw.org/) for 3D printers as this would allow printers to read USB Flash Drives rather the SD cards. The company I work for is a great believer in open-source and we would donate all our integration work to the open-source and 3D printing community.

However, I notice that the USB Host Shield is released under "GPL v2" rather than "GPLv2 or later", which would preclude integration with Marlin, which is released under the "GPL v3".

Is there any chance the license could be upgraded to either the GPL v3, or to include the wording "GPLv2 or later" in order to maintain compatibility with the GPL v3?

Information why this is necessary for the GPLv3 and GPLv2 is listed here:

https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

Thank you!

-- Marcio

**Comment by felis** [comment]
I like Lulzbot and I like my TAZ 6 :-), the whole product documentation for which is open sourced and available.

@Lauszus , @xxxajk  - do you have objections to changing the wording of the license to 'GPLv2 or later'?

**Comment by Lauszus** [comment]
I'm in for changing the license as well. I have a few 3D printers running Marlin, så I'm excited to see what they come up with :)

**Comment by xxxajk** [comment]
I've no problem with GPL2 or later...

**Comment by marcio-ao** [comment]
This is fantastic news! Another engineer and I have already done preliminary work on this and we know that we can reuse the FAT routines that Marlin already has for SD cards, so we only need the following files that implement the block-level USB mass storage access:

- address.h
- avrpin.h
- confdescparser.h
- macros.h
- masstorage.cpp
- masstorage.h
- max3421e.h
- message.cpp
- message.h
- parsetools.cpp
- parsetools.h
- printhex.h
- settings.h
- Usb.cpp
- Usb.h
- usb_ch9.h
- UsbCore.h
- usbhost.h

So for our purposes, if just those particular files were updated with the wording "GPL v2 or later", we would be able to perform the integration.

Thank you so much!

-- Marcio

**Comment by marcio-ao** [comment]
I just wanted to share some preliminary results. This is actually Marlin reading files from a USB drive. It is also driving a color LCD touch panel (another project we have been working on):

![marlinusb](https://user-images.githubusercontent.com/29129419/37605915-e30ff9d6-2b59-11e8-978d-47302ceb6044.JPG)

Printing already works, although the only glitch is that currently the drive insertion/removal is not recognized.

**Comment by xxxajk** [comment]
Very cool.
Thanks for sharing!

**Comment by marcio-ao** [comment]
Curious whether there will be a commit with the files with an updated license? This is not something I feel comfortable doing myself. I would like to replace the files I am currently using with something with the correct licenses.

**Comment by Lauszus** [comment]
Since @felis assigned himself, I was assuming that he would do it?

**Comment by marcio-ao** [comment]
Anything happening with this?

**Comment by Lauszus** [comment]
@marcio-ao I have updated the copyright header in the relevant files in https://github.com/felis/USB_Host_Shield_2.0/commit/00aa35518b618e75af5cee29297c1abfb0af969b.

**Comment by marcio-ao** [comment]
@Lauszus : Awesome! Thank you so much!

**Comment by Lauszus** [comment]
You're welcome :)

**Comment by marcio-ao** [comment]
@Lauszus : Sorry to bother you again, is there a chance you could update the license for the following files as well?

- version_helper.h
- hex_dump.h
- sink_parser.h

I'm sorry I didn't request this sooner. I got caught up in a new printer releases and I had to put this on hold for a while.

**Comment by Lauszus** [comment]
@marcio-ao sorry for the late reply, it was fixed in: https://github.com/felis/USB_Host_Shield_2.0/commit/06d5ed134a37e22575c0ce18c061d9ef115151e0.

**Comment by marcio-ao** [comment]
@Lauszus : Thank you! I was able to roll it all up as a PR to Marlin (#11115). Hopefully we will see this new feature standard in Marlin 2.0. I appreciate all the help along the way! :)

**Comment by Lauszus** [comment]
Great! Looking forward to seeing the code in the wild :)
