### ISSUE TITLE
USBFTDILoopback example

### ISSUE THREAD

**Issue by mprowe** [felis/USB_Host_Shield_2.0#372]
Hi,
I would like to use your example code with a FTDI FT232R which has a custom PID of 6015.
Currently, I am amending the cdcftdi.h. Is it possible to  instantiate an FTDI object using this PID in the  signature?

Regards, Martin

**Comment by Lauszus** [comment]
@mprowe I just pushed a fix to the FTDI driver: https://github.com/felis/USB_Host_Shield_2.0/commit/266f1355f58b77fee7f8a212928ce8e1cc6557f6.

Please re-download the library and then create the FTDI instance like so:
```C++
FTDI Ftdi(&Usb, &FtdiAsync, 0x6015);
```
