### ISSUE TITLE
why usb host shield is discontinued product?

### ISSUE THREAD

**Issue by amrithmmh** [felis/USB_Host_Shield_2.0#379]
sorry even though this is somewhat related its not an issue for usb host shield library

i would like to know if the product is still "active" or is it forgotten? (especially in sparkfun store)

**Comment by Lauszus** [comment]
The shield is not available from http://shop.tkjelectronics.dk/ until the 14th of August. You should be able to find clones all around the internet. I am not affiliated with Sparkfun in any way, so you have to contact them directly.

**Comment by amrithmmh** [comment]
@Lauszus  thanks for your reply
