### ISSUE TITLE
Arduino Blink with USB SHield

### ISSUE THREAD

**Issue by das-dipen** [felis/USB_Host_Shield_2.0#381]
Hi,
I am quite new in arduino programming. I have a Light connected via USB cable to a USB host shield on Arduino Mega 2560. Using the example provided, it keeps going. I want to control it with Visual C++ using a button. What I mean is I want it to light and stop when I press the Button and then again light up when i press the button. Can anybody help me out with this please. 
Again, i am very much new in this area. I would really appreciate if any body can help me out with this

**Comment by Lauszus** [comment]
This issue tracker is not meant for coding guidance. You should ask for help at a forum or similar. Try asking your question at the Arduino forum: http://arduino.cc/forum/.
