### ISSUE TITLE
Support for ESP32 built-in bluetooth?

### ISSUE THREAD

**Issue by MiloMindbender** [felis/USB_Host_Shield_2.0#396]
Sorry, it's not entirely clear, does this library support the built-in bluetooth on the ESP32?  (in arduino mode)

If it doesn't, is it planned?  I'd particularly like to connect Playstation 4 DualShock controllers to ESP32 by bluetooth.

**Comment by Lauszus** [comment]
No it does not and no it is not something I have planned.

**Comment by xxxajk** [comment]
If it isn't on USB, then of course not.
