### ISSUE TITLE
writing .txt files to pendrive

### ISSUE THREAD

**Issue by saikiran7714** [felis/USB_Host_Shield_2.0#398]
im using this library for my max3421e usb host controller connected to atmega2560 it is detecting my pendrive make and model but how to write to pendrive using this library . Can u please share a example for mass storage

**Comment by Lauszus** [comment]
The following line of the example shows you how to write to a text file: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/testusbhostFAT/testusbhostFAT.ino#L606.

**Comment by xxxajk** [comment]
UHS2.0 has too much for the end user to do, whereas UHS3.0 handles all the dirty details out of your way.
Just use UHS3.0 as files are MUCH easier to deal with.
