### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saikiran7714** [felis/USB_Host_Shield_2.0#400]
sir im getting this error if i run testusbhostFAT example

C:\Users\SAI\Documents\Arduino\libraries\generic_storage-master/FAT/FatFS/src/ff.c: In function 'f_write':

C:\Users\SAI\Documents\Arduino\libraries\generic_storage-master/FAT/FatFS/src/ff.c:2880:1: error: unable to find a register to spill in class 'POINTER_REGS'

}

^

C:\Users\SAI\Documents\Arduino\libraries\generic_storage-master/FAT/FatFS/src/ff.c:2880:1: error: this is the insn:

(insn 216 215 217 33 (set (reg:HI 26 r26)

    (reg/f:HI 194)) C:\Users\SAI\Documents\Arduino\libraries\generic_storage-master/FAT/FatFS/src/ff.c:2837 83 {*movhi}

 (nil))
C:\Users\SAI\Documents\Arduino\libraries\generic_storage-master/FAT/FatFS/src/ff.c:2880: confused by earlier errors, bailing out

lto-wrapper: C:\Users\SAI\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-gcc returned 1 exit status

c:/users/sai/appdata/local/arduino15/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560

**Comment by Lauszus** [comment]
Please update to the newest version of Arduino, as that is a compiler bug.
