### ISSUE TITLE
SPRESENSE from SONY

### ISSUE THREAD

**Issue by yokozawa766** [felis/USB_Host_Shield_2.0#401]
SONY developped new Arduino board , called SPRESENSE. I saw SPI interface on the main board. i have also seen modifies for ESP32 on this GitHub library and the library uses only SPI pins (MOSI, MISO, SCK, SS, INT) on ESP32, I mean the library doesn't use so many other GPIOs, so I guess this library can also develop modify for SPRESENSE.

By the way, I want new BT interfaces between SPRESENSE and Dualshock4 (PS4 Controller). ROHM has started selling new BLE (Bluetooth Light Energy) add-on board for SPRESENSE main board. I don't know sure whether this libray can use this add-on board. If not, the new BT add-on board between SPRESENSE and Dualshock4 can become business. ( I guess this usage of interface is in need of wireless communication, so only BT is enough, USB on-wire communication is not needed.)

**Comment by xxxajk** [comment]
Are you able to send me one of these?
If so, I should be able to do support for it.
Also, please note that since the ICSP connection is missing, that some modifications will be required if using the full sized shield.

**Comment by yokozawa766** [comment]
Thanks for responding. Do you mean you ban support library modification if i can send usb host shield for SPRESENSE ? Or just sending you data or link of SPRESENSE ?

**Comment by yokozawa766** [comment]
You would pointed out that mini board doesn’t have 5V power, like Spresense main board.

We cannot implement USB master-side connector on it.

 

I guess there are two choices for that issue.

-       Making usb host shield for extention i/o board of Spresense like you have mentioned .

-       Or another way is that Bluetooth metal cap module on the mini board with SPI interface.

These metalcap modules work usually by 3.3V power.

 

Let me see…

**Comment by xxxajk** [comment]
If you can send me the hardware, I can make it work, and send you something that works back.

**Comment by xxxajk** [comment]
I forgot to say, that for the effort I would be keeping the hardware in order to be able to maintain the library. I would be sending a board that will work with your setup. It isn't that difficult.

**Comment by yokozawa766** [comment]
I am making new pcb now like this. 

It will take one week probably.

 



 

I am also planning to send this hardware for you to work PS4BT on this board after this.

**Comment by yokozawa766** [comment]
Dear Andrew,

 

Today I received printed circuit board.

I will check this board from now on.

 



 

Sincerely,

Kazunori YOKOZAWA

 

From: Kazunori Yokozawa [mailto:yokozawa766@nifty.com] 
Sent: Friday, August 17, 2018 5:00 AM
To: 'felis/USB_Host_Shield_2.0' <reply@reply.github.com>; 'felis/USB_Host_Shield_2.0' <USB_Host_Shield_2.0@noreply.github.com>
Cc: 'State change' <state_change@noreply.github.com>
Subject: RE: [felis/USB_Host_Shield_2.0] SPRESENSE from SONY (#401)

 

I am making new pcb now like this. 

It will take one week probably.

 



 

I am also planning to send this hardware for you to work PS4BT on this board after this.

**Comment by yokozawa766** [comment]
Finally, implemented.

 



 

From: Kazunori Yokozawa [mailto:yokozawa766@nifty.com] 
Sent: Wednesday, August 22, 2018 9:46 PM
To: 'felis/USB_Host_Shield_2.0' <reply@reply.github.com>; 'felis/USB_Host_Shield_2.0' <USB_Host_Shield_2.0@noreply.github.com>
Cc: 'State change' <state_change@noreply.github.com>
Subject: remind: [felis/USB_Host_Shield_2.0] SPRESENSE from SONY (#401)

 

Dear Andrew,

 

Today I received printed circuit board.

I will check this board from now on.

 



 

Sincerely,

Kazunori YOKOZAWA

 

From: Kazunori Yokozawa [mailto:yokozawa766@nifty.com] 
Sent: Friday, August 17, 2018 5:00 AM
To: 'felis/USB_Host_Shield_2.0' <reply@reply.github.com>; 'felis/USB_Host_Shield_2.0' <USB_Host_Shield_2.0@noreply.github.com <mailto:USB_Host_Shield_2.0@noreply.github.com> >
Cc: 'State change' <state_change@noreply.github.com <mailto:state_change@noreply.github.com> >
Subject: RE: [felis/USB_Host_Shield_2.0] SPRESENSE from SONY (#401)

 

I am making new pcb now like this. 

It will take one week probably.

 



 

I am also planning to send this hardware for you to work PS4BT on this board after this.
