### ISSUE TITLE
[Question] Need help debugging INVALID_CSW error

### ISSUE THREAD

**Issue by marcio-ao** [felis/USB_Host_Shield_2.0#410]
Hello,

I am trying to troubleshoot a problem I am seeing with certain flash drives on our printer prototypes. I are noticing a peculiar situation where if I power on the printer with a USB drive inserted, it is able to read files just fine. But, if I insert it afterwards, it fails the initialization. This happens only on some USB drives and we've used other drives without any problems at all.

I turned on USB logging and the cause of the failure seems to be the "Invalid CSW" error. Interestingly, when I edit "massstorage.cpp" and skip the check (i.e IGNORE_INVALID_CSW=1), the drive which would otherwise fail work just fine.

```
uint8_t BulkOnly::Transaction(...) {
   ...
                if(usberr == hrSUCCESS) {
                        if(IsValidCSW(&csw, pcbw)) {
                                ...
                        } else {
                                // NOTE! Sometimes this is caused by the reported residue being wrong.
                                // Get a different device. It isn't compliant, and should have never passed Q&A.
                                // I own one... 05e3:0701 Genesys Logic, Inc. USB 2.0 IDE Adapter.
                                // Other devices that exhibit this behavior exist in the wild too.
                                // Be sure to check quirks in the Linux source code before reporting a bug. --xxxajk
                                Notify(PSTR("Invalid CSW\r\n"), 0x80);
                                #if IGNORE_INVALID_CSW == 1
                                        return MASS_ERR_SUCCESS;
                                #endif
                                ResetRecovery();
                                return MASS_ERR_INVALID_CSW;
                        }
   ...
}
```

Given the code comment, I would chalk this up as being a non-standards compliant drive, except that it works just fine if the printer is powered on *with* the drive inserted. If it was a standards compliance issue, I would not expect it to behave differently in those two cases.

So, two questions:

1) Any thoughts at to why this is happening?
2) How dangerous is it to skip the INVALID_CSW check? I worry that by skipping it I may simply be masking another problem.

I know nothing about USB protocols, so anything that can get me moving in the right direction would be very helpful!

Thank you!

-- Marcio

**UPDATE:** I am including three logs to hopefully help troubleshoot things:

1. LoadOkay.log - Successful mount of drive, drive inserted at powerup
2. LoadError.log - Unsuccessful mount of driver, drive inserted after powerup
3. LoadErrorIgnored.log - Result of forcing a return of MASS_ERR_SUCCESS on a Invalid CSW error

[LoadOkay.log](https://github.com/felis/USB_Host_Shield_2.0/files/2401696/LoadOkay.log)
[LoadError.log](https://github.com/felis/USB_Host_Shield_2.0/files/2401697/LoadError.log)
[LoadErrorIgnored.log](https://github.com/felis/USB_Host_Shield_2.0/files/2401698/LoadErrorIgnored.log)

By diffing these three files, I see that the first place where an error occurs is here:

```
TestUnitReady
-----------------
CBW.dCBWTag: 00000002
CBW:		OK
Data Stage:	OK
CSW:		OK

SCSI Error: 01
LUN: 00
```

This triggers the first "ResetRecovery", which causes all subsequent "TestUnitError" to have a "Invalid CSW". By default, this triggers another "Reset Recovery", followed by another "TestUnitError", in an infinite loop. By ignoring the "Invalid CSW" (and not triggering an additional "ResetRecovery"), it breaks the loop and allows the drive to initialize.

**Comment by marcio-ao** [comment]
Okay, we added a few print functions to IsValidCSW and found a single bit error in the returned value:

TestUnitReady
-----------------
CBW.dCBWTag: 00000013
CBW:		OK
Data Stage:	OK
CSW:Sig error
pcsw->dCSWSignature: 0x43425355
MASS_CSW_SIGNATURE: 0x53425355
Invalid CSW

It looks like reducing the clock rate on our SPI interface has cleared the error. While it is a bit peculiar that it is only affecting the first bit consistently, at least I have a workaround.

**Comment by xxxajk** [comment]
Not too surprised.
There are things that you can do to get higher speeds.
Try to make the clock and data tracks are the same length. This will help with clock v.s. data race conditions.
If you are level shifting the signals, it can be helpful to use chips that are as fast as you can obtain, or, to use a pull-up resistor and a diode. Either of these will remove latency issues a lot! If not and everything is 3.3v, then you might be seeing distortion on the signals.
Sometimes you may need to add either pull up or pull down resistors. Check your signalling with a scope, make sure it is clean.

**Comment by marcio-ao** [comment]
@xxxajk: We are actually running this via a ribbon cable of about six inches and it the cable is daisy chained over at least three devices. We scoped it up and saw that it was being driven at 1.6MHz -- diving it at ~180 kHz seems to work much better.

Will close this ticket.
