### ISSUE TITLE
board_qc running error

### ISSUE THREAD

**Issue by ashish1779** [felis/USB_Host_Shield_2.0#415]
Issue with Aruino Mega ADK

Circuits At Home 2011
USB Host Shield Quality Control Routine
Reading REVISION register... Die revision invalid. Value returned: 00
Unrecoverable error - test halted!!
0x55 pattern is transmitted via SPI
Press RESET to restart test

Simple code without including USB_Host_Shield_2.0 is running but with this library it is showing the error
"OSC did not started".
I also got "OSCOKIRQ failed to assert" error some time.

**Comment by Lauszus** [comment]
They have most likely just moved the SS and INT pins to some other pins.

**Comment by ashish1779** [comment]
No SS PIN is as it is

**Comment by Lauszus** [comment]
How have you verified that?

**Comment by Lauszus** [comment]
Closing, as it is likely a hardware issue.
