### ISSUE TITLE
Add function descriptions to (doxygen) documentation

### ISSUE THREAD

**Issue by riban-bw** [felis/USB_Host_Shield_2.0#416]
The documentation of the classes does not include any detail of what each function does, what its parameters are or what its return values are. There are in-line comments within the source code describing each function. It would be advantageous to add in-line doxygen style comments so that the documentation automatically shows this detail.

Currently, a user of the library must open the library source code and read comments to get an idea of how to use the library or they must guess (or hope there is an example that demonstrates the function). Adding parameter documentation would reduce friction to library use.

**Comment by xxxajk** [comment]
I know that the parts I wrote are documented... e.g. mass storage

**Comment by riban-bw** [comment]
@xxxajk Interesting - the docs published to the website http://felis.github.io/USB_Host_Shield_2.0/ do not show your documentation but I do see it in the downloaded source code. I wonder if the website needs to be refreshed?

**Comment by xxxajk** [comment]
@riban-bw I don't think @felis is maintaining his web site any more...
Besides, if you are using an MCU that is bigger/better than an AVR, I highly suggest using UHS30.
If you want to help porting the 2.0 drivers, the help is welcomed.

**Comment by riban-bw** [comment]
@xxxajk UHS30 does not seem to support ESP8266. @Lauszus I wonder who has such access? It would be good to update the docs and then see what needs improving.

**Comment by Lauszus** [comment]
I do and @xxxajk does. I'll update the documentation shortly.

**Comment by riban-bw** [comment]
The documentation seems to be pointing to different code than what I have checked out in that it does not have any comments for mass storage in the online docs or in the source file linked to the online docs but the git repro does have documentation comments.

**Comment by Lauszus** [comment]
The URL has changes. Please visit: https://felis.github.io/USB_Host_Shield_2.0/.

**Comment by riban-bw** [comment]
Nope! Same result. I forced refreshed the browser in case there was some cache holding old pages.

**Comment by Lauszus** [comment]
Okay. Can you send me the link the exact comments you are talking about. Maybe they have the wrong syntax for Doxygen.

**Comment by Lauszus** [comment]
No worries. I have now set Travis up to update the documentation every time a commit is pushed to the master branch: https://github.com/felis/USB_Host_Shield_2.0/commit/d41e94db492c6b474090bdd903c56eac7557129a :)

**Comment by Lauszus** [comment]
And yes some of the sources are missing documentation...
