### ISSUE TITLE
Add support for HoodLoader2

### ISSUE THREAD

**Issue by limited660** [felis/USB_Host_Shield_2.0#426]
Can support be added for [HoodLoader2](https://github.com/NicoHood/HoodLoader2)? I've tried to find the correct board name to add to avrpins.h but nothing is working for me.

**Comment by xxxajk** [comment]
Hoodloader2 is just a bootloader, I don't understand the question.

**Comment by limited660** [comment]
I believe it changes the board type because when I try to upload to 16u2 it tells me I need to define the board in avrpins.h

**Comment by xxxajk** [comment]
Are you running the library on the 16u2 or the target MCU?

**Comment by limited660** [comment]
Attempting to upload it to 16u2, that's the only way to use HID between Uno and computer

**Comment by limited660** [comment]
I'll get you the output once I get a chance to install Hoodloader2 again.

**Comment by Lauszus** [comment]
Closing as irrelevant.
