### ISSUE TITLE
Which Init to use?

### ISSUE THREAD

**Issue by riban-bw** [felis/USB_Host_Shield_2.0#427]
There are two MAX3421e::Init functions. One takes a parameter defining the length of delay after reset (minimum 1000ms). The other has almost identical code but does not include the delay and sets the GPX_VBDET flag which the other routine does not. Why are there two different functions and when should each be used? It feels like these could be consolidated into a single method.

**Comment by xxxajk** [comment]
One uses a default timeout. The other allows you to specify a timeout. 
The GPX pin is for the USB power switch.
See here: https://www.circuitsathome.com/mcu/vbus-power-control-on-usb-host-shield/
