### ISSUE TITLE
WASP Barcode Scanner not initializing

### ISSUE THREAD

**Issue by limited660** [felis/USB_Host_Shield_2.0#428]
I've been able to get a barcode parser working with a generic scanner but when I tried to use this setup at work, the WASP scanner fails to initialize. I see someone else had a similar issue [here](https://github.com/felis/USB_Host_Shield_2.0/issues/323) and that code works successfully with the scanner (as well as USBHIC_desc) but the parser in that strips out everything except numbers and letters which includes device codes, periods, and returns.  Is there a way to use HIDUniversal with OemToAscii? The scanner will not start or do anything if setup using HIDBoot<USB_HID_PROTOCOL_KEYBOARD>.

**Comment by Lauszus** [comment]
Sorry, but we can not provide an example for every combination of barcode scanners. Your best bet is to merge the two example to make it do what you want to do. A PR with a working example for your device is more than welcome.
