### ISSUE TITLE
Libarary with Omega Temperature Probe

### ISSUE THREAD

**Issue by mumairanwar92** [felis/USB_Host_Shield_2.0#433]
Hi, I'm trying to interface this omega sensor with arduino (https://www.omega.com/pptst/OS-MINIUSB.html) I'm trying to use this library to send data over serial line but apparently sensor is responding. I've tried with FTDI cable and command are sent without any issue ?
I wanted to ask if this sensor is even compatible with the library ?

**Comment by Lauszus** [comment]
I check their website briefly and it does not seem like they have published what serial chip they actually use for the USB communication. Try to plug it into a Linux computer and then run ```lsusb -v``` to figure out what device it is.

**Comment by mumairanwar92** [comment]
> I check their website briefly and it does not seem like they have published what serial chip they actually use for the USB communication. Try to plug it into a Linux computer and then run `lsusb -v` to figure out what device it is.

Thankyou for replying.
