### ISSUE TITLE
Software SPI

### ISSUE THREAD

**Issue by StijnVerhelst** [felis/USB_Host_Shield_2.0#442]
Dear,
Is it possible to use Software SPI for the USB Host Shield? It's for testing purposes. 

Kind regards,
Stijn Verhelst

**Comment by Lauszus** [comment]
Yes, you can simply define the ```USB_SPI``` macro to something else: https://github.com/felis/USB_Host_Shield_2.0/blob/06d5ed134a37e22575c0ce18c061d9ef115151e0/settings.h#L32-L35
