### ISSUE TITLE
ESP8266 board package 2.5.0 results in many compile errors

### ISSUE THREAD

**Issue by gdsports** [felis/USB_Host_Shield_2.0#449]
Issue reported on the ESP8266 repo. https://github.com/esp8266/Arduino/issues/5733

Stick with ESP8266 Arduino version 2.4.2 for now. Unfortunately, the Arduino IDE will always install the latest version which is currently 2.5.0. Use Board Manager to downgrade the version to 2.4.2.

**Comment by Lauszus** [comment]
Fixed in: https://github.com/felis/USB_Host_Shield_2.0/commit/db33d38c441444caf3563a09cf1b1742f2144f19
