### ISSUE TITLE
Data is not displayed correctly.

### ISSUE THREAD

**Issue by SkyNet26** [felis/USB_Host_Shield_2.0#456]
I use the USBHIDBootMouse.INO sketch. When you move the mouse, the dX coordinates do not change. The dX shows keystroke codes.

dx=0 dy=-5
01 00 FB 0F 00 00 00

**Comment by Lauszus** [comment]
It seems like your mouse is not using the boot protocol. See the following example on how to create a custom parser for your device: https://github.com/felis/USB_Host_Shield_2.0/tree/master/examples/HID/USBHIDJoystick.

**Comment by SkyNet26** [comment]
Thank you.
