### ISSUE TITLE
Dongle not initializing

### ISSUE THREAD

**Issue by Radzyckyj** [felis/USB_Host_Shield_2.0#469]
Hi,

So, i have a UGREEN USB Wireless Bluetooth 4.0 dongle, but when I try to run the PS3BT.ino, i get only the following message in the serial monitor:
//

PS3 Bluetooth Library Started

//
It get stucks there

Using UGREEN USB Wireless Bluetooth 4.0 Adapter
https://www.ugreen.com/product/UGREEN_USB_Bluetooth_Adapter_Wireless_Dongle_Receiver-en.html

Thanks in advance

**Comment by Lauszus** [comment]
Please see: https://github.com/felis/USB_Host_Shield_2.0#enable-debugging.
