### ISSUE TITLE
Moving mouse while printing position and events

### ISSUE THREAD

**Issue by devbrsa** [felis/USB_Host_Shield_2.0#546]
Hi,
Arduino Leonardo+USB Host shield.

How can I print any dummy value while having mouse left pressed?

Thanks,

**Comment by Lauszus** [comment]
Please see the provided example: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/HID/USBHIDBootMouse/USBHIDBootMouse.ino.

FYI this is not the place to ask general programming questions. Please use the Arduino forum or similar.
