### ISSUE TITLE
Xbox original wire controller

### ISSUE THREAD

**Issue by jcruzp** [felis/USB_Host_Shield_2.0#55]
Dear friend How must I modify Xbox Library for use with xbox original wire controller, not xbox 360, original (black) xbox. Thanks

**Comment by Jc7tee** [comment]
> "When I uncomment hub instance in USB_desc.PDE I don't obtain child access to device with product id 0289 only obtains access to hub. The product id info 0288 for hub and 0289 for device are obtain with USB spy program install in my pc."
> 
> I detect that the problem with USB_desc.PDE is that we need https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/USB_desc/USB_desc.pde#L106 uncomment because low response from Xbox hub controller

I feel like the issue I'm facing might be similar #544. I'm trying to get my xbox one controller to work with an active usb cable. The usb cable have the option to be powered externally. Using USBDeview software, I got the following. The usb external power has to be unplugged for it to work on pc.
![Untitled](https://user-images.githubusercontent.com/27125393/94365823-676a2680-0130-11eb-8a00-4ba852faf049.png)
So I concluded that I need to instances of USBHub in the hub_demo. So far I can only get one address printed and no device detected.

I'm curious as to what line in the hub_demo that was commented out as quoted. I'm not sure which line it was referring to in the current version...
