### ISSUE TITLE
"Please define board in avrpins.h"   Teeensy 4.0

### ISSUE THREAD

**Issue by arpeggio1234** [felis/USB_Host_Shield_2.0#560]
Hello, i use the Usb-host-shield library alot, very good piece of software, thanks again.
I have a little question about Teensy 4.0. I try to compile the board_qc code for it.
But couse it's new it's not in the avrpins.h file.
Can i do that myself if i ask paul Stoffregen the info, or is that a bit over my head.
I see the board info, so adding the teensy 4.0 info would not be that difficult, or is there much more to come after that and 
is that way of thinking way to simpel. And can you give me advice how to go further, and help me on the way,
maybe there is some support for teensy4 
Thanks in Advance, Dian from the Netherlands

**Comment by turkysha** [comment]
@arpeggio1234 You can do it yourself. If you know the pins it is achievable.
