### ISSUE TITLE
I2C problem

### ISSUE THREAD

**Issue by makerstorage** [felis/USB_Host_Shield_2.0#561]
I am having trouble using the Wire.begin(); directive in order to init some i2c hardware.
commenting out the Wire.begin(); let my barcode scanner work but when I use Wire.begin(); in setup for arduino uno the reader did not work. The i2c device uses the A4 A5 pins on the board.

Did anybody have that problem before?

Regards,
Nuri Erginer

**Comment by Lauszus** [comment]
I can't see how this is related to this library, as this library does not use I2C.

So I'm closing this issue. Feel free to reopen if you believe it is related to this library after all.
