### ISSUE TITLE
getDevDescr () fails on some devices.

### ISSUE THREAD

**Issue by YuuichiAkagawa** [felis/USB_Host_Shield_2.0#563]
I am trying to support the Novation Circuit. However, faild on getDevDescr().  
This device returns only 8 bytes of Device Descriptor by default address.
![circuit-failed-on-UHS2](https://user-images.githubusercontent.com/926923/99142435-3fab2f80-2698-11eb-9666-25d09c956677.png)

So I tried the Windows style method and it worked.
https://techcommunity.microsoft.com/t5/microsoft-usb-blog/how-does-usb-stack-enumerate-a-device/ba-p/270685

Usb.cpp
https://github.com/felis/USB_Host_Shield_2.0/blob/master/Usb.cpp#L718-L719
```
        // Get device descriptor
//        rcode = getDevDescr(0, 0, sizeof (USB_DEVICE_DESCRIPTOR), (uint8_t*)buf);
        rcode = getDevDescr(0, 0, 8, (uint8_t*)buf);
```

usbh_midi.cpp
https://github.com/YuuichiAkagawa/USBH_MIDI/commit/a718bf6a4372baf022c3e708f4fe816df93894fa#

Then
![circuit-fixed-on-UHS2](https://user-images.githubusercontent.com/926923/99142462-7f721700-2698-11eb-80f2-a9336924d3de.png)

**Comment by Lauszus** [comment]
Very interesting. Have you seen any other devices that has this behavior?

**Comment by YuuichiAkagawa** [comment]
I don't know other devices. I encountered it for the first time.

**Comment by Lauszus** [comment]
Okay. For now we can just add it to your MIDI drivers. Feel free to send a PR once the code is ready.

**Comment by Lauszus** [comment]
Closing, as https://github.com/felis/USB_Host_Shield_2.0/pull/566 has been merged.
