### ISSUE TITLE
Multi Keyboards to HUB + identify what is typed on which

### ISSUE THREAD

**Issue by jacceko** [felis/USB_Host_Shield_2.0#565]
Is possibility to identify 4 (identical)  keyboards connected to one usb hub? I want to know what is typed on which keyboard. (and do that again after power loss, and then make the same identification (like on linux - check the keyboard on which hub port number is connected).  Is it possibility to do that, is some one which have experience with connection of more than one identical keyboards.

**Comment by Lauszus** [comment]
You could modify `hidcomposite.cpp` to store the `iSerialNumber` of the device descriptor: https://github.com/felis/USB_Host_Shield_2.0/blob/master/usb_ch9.h#L118 similarly how the VID and PID is stored: https://github.com/felis/USB_Host_Shield_2.0/blob/master/hidcomposite.cpp#L188-L189.
