### ISSUE TITLE
Please Issue a new Release

### ISSUE THREAD

**Issue by Jonas-commits** [felis/USB_Host_Shield_2.0#579]
The latest release is almost 3 years old and does not contain crucial bugfixes like fixing #577. Please issue a new release.

**Comment by Lauszus** [comment]
Thanks for reminding me. I have just made a new release: https://github.com/felis/USB_Host_Shield_2.0/releases/tag/1.4.0.

**Comment by DanielGibson** [comment]
Awesome, thanks a lot! :tada:
