### ISSUE TITLE
Send and receive commands to/from USB device using USB Host Shield

### ISSUE THREAD

**Issue by mrcg** [felis/USB_Host_Shield_2.0#595]
Hello,
i have already tried to find some examples but could not find.
Hopefully this is the right place to get feedback from experts.

Currently i am controlling a USB turntable via serial monitor from a PC.
I only need a serial terminal (like the one from the Arduino installation) to send some commands to the turntable so that it starts rotating. The only thing i need to do is to set the baudrate to 115200 and line feed to (CR). The turntable sends back some simple status information. See illustration and screenshot (terminal window from PC which is connected to the turntable) below.

![Arduino_Serial_Monitor_Working_Movement](https://user-images.githubusercontent.com/4404991/106199530-dffff300-61b5-11eb-8200-2afe412ff0aa.JPG)

I would like to control the turntable with Arduino Uno and USB Host Shield so that all the commands are sent from the Arduino to the Turntable. Beside this the Arduino need to read the feedback to trigger next actions.
It seems to be easy thing but i could not find anything in the internet how to do this. I was not able to modify existing code from e.g. XBox or PS3/4 controller, barcode reader.

My questions:
1. Is it possible to use the USB Host Shield to do what i want to do?
2. What would be a very easy arduino code to send the command/string "move 312" to the turntable and read out the feedback send from the turntable to the Arduino? Can somebody help me here?

Thanks for your help and support!
Chris

`
Current Situation:

      ##########################                     ###################
      # PC (COM4, 115200 Baud) #--------USB----------# Turntable (USB) #
      ##########################                     ###################

                     >>>>>>>>>>>>>>> move 312 >>>>>>>>>>>>>>>

                     <<<<<<<<<<<< status running <<<<<<<<<<<<

                     <<<<<<<<<<<< status stopped <<<<<<<<<<<<

#########################################################################
Planned Situation:

      ###################                     ###################
      #    Arduino Uno  #                     #                 #
      #        +        #--------USB----------# Turntable (USB) #
      # USB Host Shield #                     #                 #
      ###################                     ###################

                     >>>>>>>>>>>>>>> move 312 >>>>>>>>>>>>>>>

                     <<<<<<<<<<<< status running <<<<<<<<<<<<

                     <<<<<<<<<<<< status stopped <<<<<<<<<<<<

#########################################################################

**Comment by Lauszus** [comment]
Yes that is differently possible.

This is not the place to ask for programming help. Please post your question on a forum like the official Arduino forum: <https://forum.arduino.cc/>.
