### ISSUE TITLE
Serial communication over USB Host

### ISSUE THREAD

**Issue by slavendam** [felis/USB_Host_Shield_2.0#604]
Hi,
I'm trying to make communication between 2 devices with USB Host.
Device1 has USB Host Shield, and Device2 has USB-to-UART (FTDI). 
1. Can I send data from Device1 to Device2 with serial communication (Software serial?)?
2. If both device are Arduinos, can I do programming dev2 from dev1 (send .hex file)? Are there some examples or projects with this feature?
3. Does anyone have experience with ESP32 and USB Host Shield?

Thanks :)

**Comment by Lauszus** [comment]
1. Yes you can. See the following example: https://github.com/felis/USB_Host_Shield_2.0/tree/master/examples/ftdi/USBFTDILoopback
2. You basically want to implement avrdude on the microcontroller. I'm only aware of this library that implements it on an Android device: https://github.com/ksksue/PhysicaloidLibrary. You can base your code on that or the avrdude source code.
3. Check out the issue tracker for other people's experience with using the ESP32: https://github.com/felis/USB_Host_Shield_2.0/issues?q=esp32
