### ISSUE TITLE
How to recover from OUT-NAK?

### ISSUE THREAD

**Issue by YuuichiAkagawa** [felis/USB_Host_Shield_2.0#607]
SNDFIFO is not cleared when USB::OutTransfer() exits when it reaches nak_limit.
Probably, when the next data is sent in this state, SNDFIFO becomes a double buffer operation.
https://youtu.be/ZxuxnGrov9U

![NAK-retransmission](https://user-images.githubusercontent.com/926923/110213745-af158b00-7ee4-11eb-9844-05df04f2735e.png)

When HRSLT returns non-zero, writing 0 to SNDBC seems to clear the SNDFIFO.
https://github.com/felis/USB_Host_Shield_2.0/compare/master...YuuichiAkagawa:pr_outnak_fix
https://github.com/YuuichiAkagawa/USB_Host_Shield_2.0/blob/c56eee9f163b25c2e4be76bd70f44bbf3c17cb8f/Usb.cpp#L390-L396

https://youtu.be/ZxuxnGrov9U?t=29
![NAK-discard](https://user-images.githubusercontent.com/926923/110213766-c785a580-7ee4-11eb-91c1-4569f71a16b7.png)

**Comment by Lauszus** [comment]
Good find. Can you send a PR with the fix?

**Comment by YuuichiAkagawa** [comment]
Yes I will. 
However, I have only tested MIDI driver + bulk transfer. Can anyone test in other cases?

**Comment by Lauszus** [comment]
Fixed in #617
