### ISSUE TITLE
Naming conflicts with shared control identifiers (ButtonEnum)

### ISSUE THREAD

**Issue by dmadison** [felis/USB_Host_Shield_2.0#611]
Within the `ButtonEnum` used to list controls ([`controllerEnums.h`](https://github.com/felis/USB_Host_Shield_2.0/blob/28a75dea6b615b517205932e243c583fed85b5eb/controllerEnums.h)) the buttons are not unique. This creates a problem where two buttons with separate names but the same ID cannot be used on the same controller.

This occurs on the new Xbox Core controller used in the Series S / Series X, which has both a `VIEW` button (`4`, used with Xbox One) and a `SHARE` button (also `4`, used with PS4). Because they share the same value the `getButtonPress` function cannot distinguish between them.

To me it seems that the best solution would be to remove the values in the enum definition so that each control surface ID is unique, then each controller class could handle the parsing on a case-by-case basis. This would also allow you to do controller-specific transformations of inputs without affecting the other controller classes. The downside is that while this could maintain compatibility with programs that use the controls by name, it would unfortunately break compatibility with programs that use the enum values by number (if there are any).

I can look into making that change myself, but I'm unsure how much of a change to the public API you're comfortable with.

**Comment by Lauszus** [comment]
I do not believe anybody ues the enums by number, so I'm fine with breaking up the enums.

A pull request with the changes would be awesome :)
