### ISSUE TITLE
Cannot send midi messages to a Nux MG300

### ISSUE THREAD

**Issue by wo2507** [felis/USB_Host_Shield_2.0#616]
hello,
i'm trying to send midi messages to a Nux mg-300 (guitar effect).
the code is work well with Zoom MS50G, but not work to my Nux MG300

here is my test code 

`
 

#include <Usb.h>
#include <usbhub.h>
#include <usbh_midi.h>

USB Usb;
USBH_MIDI Midi(&Usb);

void setup()
{ 
  pinMode( 7, OUTPUT);  // For the sheild
  digitalWrite( 7, HIGH); // for the sheild
  if (Usb.Init() == -1)
  {   
    while(1);               // Halt
  }
  delay(200);  
}

void loop()
{
   //test to nux mg300
   SendMIDIPC(Patch1A);
   delay(1000);   
   SendMIDIPC(Patch2A);
   delay(1000); 
   
   //test to zoom ms50g
   /*tunerOn();
   delay(1000);
   tunerOff();
   delay(1000);*/
       
}

// Patch Changer

void SendMIDIPC(){
}

///////////=========== this is for activated/deactivated tuner on zoom ms50g ===========////////////

/*void tunerOn(){
}

void tunerOff()
{
  
}
*/
.

**Comment by YuuichiAkagawa** [comment]
Run https://github.com/YuuichiAkagawa/USBH_MIDI/blob/master/examples/USB_MIDI_desc/USB_MIDI_desc.ino

**Comment by YuuichiAkagawa** [comment]
reference https://www.vguitarforums.com/smf/index.php?PHPSESSID=bbda9e64154c4340ebc6ce2011ed2a9d&topic=29139.msg212388#msg212388

**Comment by eggyerdiyus271013** [comment]
Hiii, this issue solved already ?
