### ISSUE TITLE
Simple code for a mouse using the USB.h class

### ISSUE THREAD

**Issue by vladislavzorin** [felis/USB_Host_Shield_2.0#635]
Hi,
Tell me how I would get data packets from the mouse in the form of "00000001" using USB classes. Is there a sample code for this. You have an example where the mouse is connected, I need the same thing only without data conversion, I need to get the bare data. help please

**Comment by Lauszus** [comment]
Simply just create a class that inherits `HIDReportParser` and override the `parse` function and print the data:

```C++
class CustomMouseReportParser : public HIDReportParser {
public:
    void Parse(USBHID *hid, bool is_rpt_id, uint8_t len, uint8_t *buf) {
        for (uint8_t i = 0; i < len; i++) {
            Serial.print(buf[i]);
            Serial.write(' ');
        }
        Serial.println();
    }
}
```

Create the instances:

```C++
USB Usb;
USBHub Hub(&Usb);
HIDBoot<USB_HID_PROTOCOL_MOUSE> HidMouse(&Usb);
CustomMouseReportParser Prs;
```

And then set the parser in setup:

```C++
HidMouse.SetReportParser(0, &Prs);
```
