### ISSUE TITLE
How to add support for Adafruit Feather nRF52832?

### ISSUE THREAD

**Issue by ar664** [felis/USB_Host_Shield_2.0#639]
So I looked at the commit adding nRF52840:
https://github.com/felis/USB_Host_Shield_2.0/commit/a56613ae661e473b911f85048a5405cb4c969914

Is it the same way to add it using a similar referece?:

https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/variants/feather_nrf52832/variant.cpp

https://github.com/felis/USB_Host_Shield_2.0/blob/b6511306f1d991098e36bb0bce46db98f2d93ac4/avrpins.h#L1320-L1322

**Comment by Lauszus** [comment]
Yes it's the same steps. Check out his PR: https://github.com/felis/USB_Host_Shield_2.0/pull/614
