### ISSUE TITLE
 "Start ⸮⸮⸮" - HID keyboard

### ISSUE THREAD

**Issue by ParadoxArudino** [felis/USB_Host_Shield_2.0#663]
Hi,
I'm quite new to Arduino and this is my 3rd project, but I am planning to have a USB keyboard as Main input. At the moment, I have tested out HIDBootKbd and HIDBootMultiMediaKbd, however both serial monitors return "Start ⸮⸮⸮" (pressed 'a' once, different letters give different symbol combinations). Am I doing something wrong/ have to add something. This is the case with multiple different keyboards however I am planning to use the A8 mini keyboard, without having the touchpad to do anything.

Thanks for your help, Paradox

**Comment by Lauszus** [comment]
You need to set the baud rate in the serial monitor to match the speed of the call to `Serial.begin`.

In this case you need to set it to 115200.
