### ISSUE TITLE
USB Host Shield 2.0 with USB mouse wheel

### ISSUE THREAD

**Issue by bobofishisgood** [felis/USB_Host_Shield_2.0#711]
Hello

I used Arduino UNO、USB Host Shield with library and they can work, but I want to print “USB mouse wheel value” in serial monitor , how to edit the code?

Thanks
bobofishisgood

**Comment by tmk** [comment]
Try examples/HID/USBHIDMultimediaKbd/ . You can see mouse data probably.

Apply this patch, it won't display anything without the pathch. 
https://github.com/felis/USB_Host_Shield_2.0/issues/660#issuecomment-901051550

**Comment by bobofishisgood** [comment]
Hi tmk,

 Is good refer answer to me 

Thanks
bobofishisgood
