### ISSUE TITLE
Connecting multiple devices with the same descriptors and managing them in the sequence I need

### ISSUE THREAD

**Issue by Navigatoroleg** [felis/USB_Host_Shield_2.0#721]

**Comment by Lauszus** [comment]
What is the issue? Please write a clear description.

**Comment by Navigatoroleg** [comment]
> В чем проблема? Пожалуйста, напишите четкое описание.

I'm sorry, the theme was created by accident. In the previous ticket, I received a complete answer to the problem. but I still have one more question, namely how to connect, for example, 5 identical devices with the same descriptors (for example, the stm32 board) to the hub and send commands to a specific device in the order I need.

**Comment by Navigatoroleg** [comment]
> What is the issue? Please write a clear description.

I'm sorry, the theme was created by accident. In the previous ticket, I received a complete answer to the problem. but I still have one more question, namely how to connect, for example, 5 identical devices with the same descriptors (for example, the stm32 board) to the hub and send commands to a specific device in the order I need.

**Comment by touchgadget** [comment]
Change the issue title because it is really confusing.

If you have control of the USB software running on the STM32 boards, change Serial string so the boards have unique values. Or if easier, change the USB product ID to unique values. If you have spare GPIOs, allocate 3 to select a value 0..7. Read the pins and set the USB PID or USB serial number string according to this value.

**Comment by Navigatoroleg** [comment]
> Change the issue title because it is really confusing.
> 
> If you have control of the USB software running on the STM32 boards, change Serial string so the boards have unique values. Or if easier, change the USB product ID to unique values. If you have spare GPIOs, allocate 3 to select a value 0..7. Read the pins and set the USB PID or USB serial number string according to this value.

Unfortunately, I do not have the opportunity to change the stm firmware. Is it possible to implement this using the hub library, for example, to turn on the power alternately and assign it number 1 where the first device was determined, and so on?

**Comment by touchgadget** [comment]
I have never tried this library with a hub. If you have, for example, 2
identical USB CDC ACM devices see if this works. You can generalize for N
devices.

```
USB Usb;
USBHub Hub(&Usb);
ACMAsyncOper  AsyncOper;
ACM           Acm1(&Usb, &AsyncOper);
ACM           Acm2(&Usb, &AsyncOper);

in loop()

if (Acm1.isReady()) {
    ...
}
if (Acm2.isReady()) {
    ...
}
```
