### ISSUE TITLE
How to get joystick values from the main .ino sketch? 

### ISSUE THREAD

**Issue by Istria1704** [felis/USB_Host_Shield_2.0#724]
I apologise beforehand if I'm overlooking something trivial, but I can't find a way to access the USB HID Joystick example values from the ino sketch. Only from the cpp sketch (evt=>Z2). 

Should I be able to get the values from the main ino sketch as well somehow? I don't know how else I would implement this (joystick input) part of my project with the rest (motor control, rgb strips, etc).

Thanks in advance.

**Comment by Lauszus** [comment]
The easiest is if fx make buttons a member of the `JoystickReportParser` class and then you can access it in the .ino file fx using `joy.getButtons()`
