### ISSUE TITLE
Add support for the new MAX3221E boards

### ISSUE THREAD

**Issue by jLynx** [felis/USB_Host_Shield_2.0#744]
Would it be possible to add support for the MAX3221E based boards. 
![image](https://user-images.githubusercontent.com/4393979/195422234-f888e36d-e014-4b38-a83d-a9ef90dae3c6.png)
Everything seems to be identical apart from the main IC

**Comment by xxxajk** [comment]
MAX3221E is an RS232 IC... looks like you got yourself a fake board, with a fake IC. Congratulations.

**Comment by Lauszus** [comment]
MAX3221E is a RS232 IC. Are you sure it really is a MAX3221E on your board?

**Comment by jLynx** [comment]
![IMG_20221012_175855](https://user-images.githubusercontent.com/4393979/196764673-d693caa0-d458-4f20-b193-6281536506e3.jpg)
Yep, it is. It's also a bit of a paperweight. So I was able to get a full refund on Aliexpress. I have since ordered another one from another seller. Hopefully this one doesn't swap out the photos after ordering.
