### ISSUE TITLE
Arduino Due not supported?

### ISSUE THREAD

**Issue by ns130291** [felis/USB_Host_Shield_2.0#76]
I am trying to compile the ADK samples for the Arduino Due and get the following error messages:

```
Arduino: 1.5.5-r2 (Windows 7), Board: "Arduino Due (Programming Port)"

In file included from Usb.h:36,
                 from adk.h:23,
                 from term_test.ino:1:
usbhost.h:73: error: #error "No SPI entry in usbhost.h"
usbhost.h: In static member function 'static void SPi<SPI_CLK, SPI_MOSI, SPI_MISO, SPI_SS>::init()':
usbhost.h:54: error: 'SPCR' was not declared in this scope
usbhost.h:55: error: 'SPSR' was not declared in this scope
In file included from Usb.h:36,
                 from adk.h:23,
                 from term_test.ino:1:
usbhost.h: In member function 'void MAX3421e<SPI_SS, INTR>::regWr(uint8_t, uint8_t)':
usbhost.h:134: error: 'SPDR' was not declared in this scope
usbhost.h:135: error: 'SPSR' was not declared in this scope
usbhost.h:135: error: 'SPIF' was not declared in this scope
usbhost.h:137: error: 'SPSR' was not declared in this scope
usbhost.h:137: error: 'SPIF' was not declared in this scope
usbhost.h: In member function 'uint8_t* MAX3421e<SPI_SS, INTR>::bytesWr(uint8_t, uint8_t, uint8_t*)':
usbhost.h:155: error: 'SPDR' was not declared in this scope
usbhost.h:157: error: 'SPSR' was not declared in this scope
usbhost.h:157: error: 'SPIF' was not declared in this scope
usbhost.h:162: error: 'SPSR' was not declared in this scope
usbhost.h:162: error: 'SPIF' was not declared in this scope
usbhost.h: In member function 'uint8_t MAX3421e<SPI_SS, INTR>::regRd(uint8_t)':
usbhost.h:190: error: 'SPDR' was not declared in this scope
usbhost.h:191: error: 'SPSR' was not declared in this scope
usbhost.h:191: error: 'SPIF' was not declared in this scope
usbhost.h:193: error: 'SPSR' was not declared in this scope
usbhost.h:193: error: 'SPIF' was not declared in this scope
usbhost.h: In member function 'uint8_t* MAX3421e<SPI_SS, INTR>::bytesRd(uint8_t, uint8_t, uint8_t*)':
usbhost.h:212: error: 'SPDR' was not declared in this scope
usbhost.h:213: error: 'SPSR' was not declared in this scope
usbhost.h:213: error: 'SPIF' was not declared in this scope
usbhost.h:217: error: 'SPSR' was not declared in this scope
usbhost.h:217: error: 'SPIF' was not declared in this scope
usbhost.h: In member function 'int8_t MAX3421e<SPI_SS, INTR>::Init()':
usbhost.h:272: error: 'spi' has not been declared
usbhost.h: In member function 'int8_t MAX3421e<SPI_SS, INTR>::Init(int)':
usbhost.h:309: error: 'spi' has not been declared
In file included from Usb.h:37,
                 from adk.h:23,
                 from term_test.ino:1:
UsbCore.h: At global scope:
UsbCore.h:27: error: 'P10' was not declared in this scope
UsbCore.h:27: error: 'P9' was not declared in this scope
UsbCore.h:27: error: template argument 1 is invalid
UsbCore.h:27: error: template argument 2 is invalid
UsbCore.h:27: error: invalid type in declaration before ';' token
In file included from Usb.h:37,
                 from adk.h:23,
                 from term_test.ino:1:
UsbCore.h:176: error: expected class-name before '{' token
term_test.ino: In function 'void setup()':
term_test:20: error: 'class USB' has no member named 'Init'
```

**Comment by LASKER17** [comment]
Hi, Lauszus, Can you help me?? i have arduino 1.
when I run the program board_qc, the serial monitor shows me this

Circuits At Home 2011
USB Host Shield Quality Control Routine
Reading REVISION register... Die revision 03
SPI long test. Transfers 1MB of data. Each dot is 64K
Test failed.  Value written: 01 read: 00
Unrecoverable error - test halted!!
0x55 pattern is transmitted via SPI
Press RESET to restart test

**Comment by Lauszus** [comment]
@LASKER17 what shield are you using?

**Comment by LASKER17** [comment]
Lauszus i'm using the arduino UNO

**Comment by Lauszus** [comment]
Okay, but what USB Host shield are you using? :)

**Comment by LASKER17** [comment]
I have this one

**Comment by Lauszus** [comment]
@LASKER17 you didn't send a link?

**Comment by LASKER17** [comment]
No, I sent a picture, but I have a usb host shield Keyes

@LASKER17 <https://github.com/LASKER17> you didn't send a link?

—
Reply to this email directly or view it on GitHub
<https://github.com/felis/USB_Host_Shield_2.0/issues/76#issuecomment-159071788>
.

**Comment by Lauszus** [comment]
If you want to attach a picture, you should attach it via the web GUI. Anyway please buy the official shield from either: http://shop.tkjelectronics.dk/product_info.php?products_id=43 or https://www.circuitsathome.com/products-page/arduino-shields, as there is all kind of weird issues with the Chinese clones.

**Comment by xxxajk** [comment]
Many other shields are UNO ONLY. You get what you pay for.
Buy one from circuitsathome.  Circuitsathome UHS works on ALL arduino
variants without any problems.

On Tue, Nov 24, 2015 at 8:36 AM, Kristian Sloth Lauszus <
notifications@github.com> wrote:

> If you want to attach a picture, you should attach it via the web GUI.
> Anyway please buy the official shield from either:
> http://shop.tkjelectronics.dk/product_info.php?products_id=43 or
> https://www.circuitsathome.com/products-page/arduino-shields, as there is
> all kind of weird issues with the Chinese clones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felis/USB_Host_Shield_2.0/issues/76#issuecomment-159269359>
> .
>



-- 
Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by Lauszus** [comment]
And you will get support on top of that ;)
