### ISSUE TITLE
Purchase link from readme is not valid

### ISSUE THREAD

**Issue by matihuf** [felis/USB_Host_Shield_2.0#772]
Link from readme is not valid [http://shop.tkjelectronics.dk/product_info.php?products_id=43]( http://shop.tkjelectronics.dk/product_info.php?products_id=43). I bought a clone from aliexpress, but it doesn't work as expected. I discovered that instead of a 74AHC125 chip, I have two 74HCT125s. If there is currently no company that makes this board, is there a valid board schematic somewhere?
![obraz](https://user-images.githubusercontent.com/7207471/229354822-46976a16-110b-4049-98c9-1073b32901de.png)

**Comment by touchgadget** [comment]
See the following for information including schematics for boards that the cloners copy. 

https://chome.nerpa.tech/

**Comment by matihuf** [comment]
Founded it also here https://web.archive.org/web/20230125120018/http://www.tkjelectronics.dk/uploads/usbhost/UHS_20.pdf
