### ISSUE TITLE
please close

### ISSUE THREAD

**Issue by Jtonna** [felis/USB_Host_Shield_2.0#798]

**Comment by Jtonna** [comment]
Discussion Link for the the Arduino Discord -> https://discord.com/channels/420594746990526466/1194936441545965598/1194936441545965598

OR join manually from https://support.arduino.cc/hc/en-us/articles/4405329164178-Join-the-official-Arduino-Discord-server
Under Hardware Help ->search for Hanging at USB_DETACHED_SUBSTATE_WAIT_FOR_DEVICE state when connected to certain computers.

I would prefer to keep resolutions in this thread not on discord, but i would like extra coverage and support on this issue

**Comment by xndhn** [comment]
How can I customize my own wireless mouse? Can you provide a specific tutorial?

**Comment by Jtonna** [comment]
> How can I customize my own wireless mouse? Can you provide a specific tutorial?

I cant provide a tutorial but look at my linked repository i put some information there to put you on the right track
