### ISSUE TITLE
Arduino Yun

### ISSUE THREAD

**Issue by MetallianFR68** [felis/USB_Host_Shield_2.0#91]
Hi,

I have an arduino UNO + official USB HOST SHIELD 2.0
I managed to connect my SIXAXIS controller both via USB and a BLUETOOTH DONGLE
It was pretty straightforward

My goal is to send the SIXAXIS data to my robot using wifi
I therefore bought an official wifi shield
But I realized that both USB and WIFI shields can't work together :-(
Both are using the ICSP pins. 
Only the first connected card is working

Then I bought an Arduino YUN card because it has WIFI + USB HOST integrated
Now I realize that the YUN card is not a 100% arduino board
It's ARDUINO / LINUX
In fact the USB port and the WIFI controller is controlled by the LINUX side of the card, not the arduino side.
Is there any chance to make the YUN work with my SIXAXIS controller with this library ?

**Comment by Lauszus** [comment]
I just had a look at this issue again.

You should simply remove:
```C++
while (!Serial);
while (!Serial1);
```
